/*
	@UVType AS NVARCHAR(10) = 'Unit', 
	@Signature AS NVARCHAR(50) = 'P4', 
	@Caterogy AS NVARCHAR(50) = 'Select All', 
	@Channel AS NVARCHAR(20) = 'O+O', 
	@SubGroup AS NVARCHAR(50) = 'Select All', 
	@SubCat AS NVARCHAR(50) = 'Select All', 
	@SubGroupBP AS NVARCHAR(50) = 'Select All',
	@Hero as nvarchar(100) = 'Select All'

	select * from fnc_FC_FM_Original
	(
		'LLD',-->Division	nvarchar(3) = '', not null
		'',-->@Signature		NVARCHAR(50) = '', 
		'',-->@Caterogy		NVARCHAR(50) = '', -->Select All = ''	
		'',-->@SubCat			NVARCHAR(50) = '', -->Select All = ''
		'O+O',-->@Channel		NVARCHAR(20) = '', 
		'',-->@SubGroup		NVARCHAR(50) = '', -->Select All = ''
		'',-->@SubGroupBP		NVARCHAR(50) = '',-->Select All = ''
		''-->@Hero
	)
*/
Alter function fnc_FC_FM_Original
(
	@division		nvarchar(3) = '',
	--@UVType			NVARCHAR(10) = '',--//U/V 
	@Signature		NVARCHAR(50) = '', 
	@Caterogy		NVARCHAR(50) = '', -->Select All = ''	
	@SubCat			NVARCHAR(50) = '', -->Select All = ''
	@Channel		NVARCHAR(20) = '', 
	@SubGroup		NVARCHAR(50) = '', -->Select All = ''
	@SubGroupBP		NVARCHAR(50) = '',-->Select All = ''
	@Hero			nvarchar(100) = ''
)
returns @tmp table
(
	[SO Forecasting lines] [nvarchar](300) NULL,
	[Product type] [varchar](50) NULL,
	[Signature] [nvarchar](255) NULL,
	[CAT/Axe] [nvarchar](255) NULL,
	[SUB CAT/ Sub Axe] [nvarchar](255) NULL,
	[GROUP/ Class] [nvarchar](255) NULL,
	[Ref. Code] [nvarchar](20) NULL,
	[SUB GROUP/ Brand] [nvarchar](300) NULL,
	[HERO] [nvarchar](255) NULL,
	[Channel] [nvarchar](4000) NOT NULL,
	[Product status] [nvarchar](255) NULL,
	[Time series] [nvarchar](4000) NOT NULL,
	[SIT] [int] NOT NULL,
	[SIT Day] [int] NOT NULL,
	[SOH] [int] NOT NULL,
	[MTD SI] [int] NOT NULL,
	[Total GIT] [int] NOT NULL,
	[GIT M0] [int] NOT NULL,
	[GIT M1] [int] NOT NULL,
	[GIT M2] [int] NOT NULL,
	[GIT M3] [int] NOT NULL,
	[AVE P3M Y-1] [int] NOT NULL,
	[AVE F3M Y-1] [int] NOT NULL,
	[AVE P3M Y0] [int] NOT NULL,
	[AVE F3M Y0] [int] NOT NULL,
	[%F3M Y0/ P3M Y0] [numeric](18, 2) NULL,
	[%F3M Y-1/ P3M Y-1] [numeric](18, 2) NULL,
	[SLOB] [int] NOT NULL,
	[Y-2 (u) M1] [int] NOT NULL,
	[Y-2 (u) M2] [int] NOT NULL,
	[Y-2 (u) M3] [int] NOT NULL,
	[Y-2 (u) M4] [int] NOT NULL,
	[Y-2 (u) M5] [int] NOT NULL,
	[Y-2 (u) M6] [int] NOT NULL,
	[Y-2 (u) M7] [int] NOT NULL,
	[Y-2 (u) M8] [int] NOT NULL,
	[Y-2 (u) M9] [int] NOT NULL,
	[Y-2 (u) M10] [int] NOT NULL,
	[Y-2 (u) M11] [int] NOT NULL,
	[Y-2 (u) M12] [int] NOT NULL,
	[Y-1 (u) M1] [int] NOT NULL,
	[Y-1 (u) M2] [int] NOT NULL,
	[Y-1 (u) M3] [int] NOT NULL,
	[Y-1 (u) M4] [int] NOT NULL,
	[Y-1 (u) M5] [int] NOT NULL,
	[Y-1 (u) M6] [int] NOT NULL,
	[Y-1 (u) M7] [int] NOT NULL,
	[Y-1 (u) M8] [int] NOT NULL,
	[Y-1 (u) M9] [int] NOT NULL,
	[Y-1 (u) M10] [int] NOT NULL,
	[Y-1 (u) M11] [int] NOT NULL,
	[Y-1 (u) M12] [int] NOT NULL,
	[Y0 (u) M1] [int] NOT NULL,
	[Y0 (u) M2] [int] NOT NULL,
	[Y0 (u) M3] [int] NOT NULL,
	[Y0 (u) M4] [int] NOT NULL,
	[Y0 (u) M5] [int] NULL,
	[Y0 (u) M6] [int] NULL,
	[Y0 (u) M7] [int] NULL,
	[Y0 (u) M8] [int] NULL,
	[Y0 (u) M9] [int] NULL,
	[Y0 (u) M10] [int] NULL,
	[Y0 (u) M11] [int] NULL,
	[Y0 (u) M12] [int] NULL,
	[Y+1 (u) M1] [int] NULL,
	[Y+1 (u) M2] [int] NULL,
	[Y+1 (u) M3] [int] NULL,
	[Y+1 (u) M4] [int] NULL,
	[Y+1 (u) M5] [int] NULL,
	[Y+1 (u) M6] [int] NULL,
	[Y+1 (u) M7] [int] NULL,
	[Y+1 (u) M8] [int] NULL,
	[Y+1 (u) M9] [int] NULL,
	[Y+1 (u) M10] [int] NULL,
	[Y+1 (u) M11] [int] NULL,
	[Y+1 (u) M12] [int] NULL,
	[(m-1)_Y0 (u) M1] [int] NOT NULL,
	[(m-1)_Y0 (u) M2] [int] NOT NULL,
	[(m-1)_Y0 (u) M3] [int] NOT NULL,
	[(m-1)_Y0 (u) M4] [int] NOT NULL,
	[(m-1)_Y0 (u) M5] [int] NOT NULL,
	[(m-1)_Y0 (u) M6] [int] NOT NULL,
	[(m-1)_Y0 (u) M7] [int] NOT NULL,
	[(m-1)_Y0 (u) M8] [int] NOT NULL,
	[(m-1)_Y0 (u) M9] [int] NOT NULL,
	[(m-1)_Y0 (u) M10] [int] NOT NULL,
	[(m-1)_Y0 (u) M11] [int] NOT NULL,
	[(m-1)_Y0 (u) M12] [int] NOT NULL,
	[(m-1)_Y+1 (u) M1] [int] NOT NULL,
	[(m-1)_Y+1 (u) M2] [int] NOT NULL,
	[(m-1)_Y+1 (u) M3] [int] NOT NULL,
	[(m-1)_Y+1 (u) M4] [int] NOT NULL,
	[(m-1)_Y+1 (u) M5] [int] NOT NULL,
	[(m-1)_Y+1 (u) M6] [int] NOT NULL,
	[(m-1)_Y+1 (u) M7] [int] NOT NULL,
	[(m-1)_Y+1 (u) M8] [int] NOT NULL,
	[(m-1)_Y+1 (u) M9] [int] NOT NULL,
	[(m-1)_Y+1 (u) M10] [int] NOT NULL,
	[(m-1)_Y+1 (u) M11] [int] NOT NULL,
	[(m-1)_Y+1 (u) M12] [int] NOT NULL,
	[B_Y0_M1] [int] NULL,
	[B_Y0_M2] [int] NULL,
	[B_Y0_M3] [int] NULL,
	[B_Y0_M4] [int] NULL,
	[B_Y0_M5] [int] NULL,
	[B_Y0_M6] [int] NULL,
	[B_Y0_M7] [int] NULL,
	[B_Y0_M8] [int] NULL,
	[B_Y0_M9] [int] NULL,
	[B_Y0_M10] [int] NULL,
	[B_Y0_M11] [int] NULL,
	[B_Y0_M12] [int] NULL,
	[B_Y+1_M1] [int] NULL,
	[B_Y+1_M2] [int] NULL,
	[B_Y+1_M3] [int] NULL,
	[B_Y+1_M4] [int] NULL,
	[B_Y+1_M5] [int] NULL,
	[B_Y+1_M6] [int] NULL,
	[B_Y+1_M7] [int] NULL,
	[B_Y+1_M8] [int] NULL,
	[B_Y+1_M9] [int] NULL,
	[B_Y+1_M10] [int] NULL,
	[B_Y+1_M11] [int] NULL,
	[B_Y+1_M12] [int] NULL,
	[PB_Y+1_M1] [int] NULL,
	[PB_Y+1_M2] [int] NULL,
	[PB_Y+1_M3] [int] NULL,
	[PB_Y+1_M4] [int] NULL,
	[PB_Y+1_M5] [int] NULL,
	[PB_Y+1_M6] [int] NULL,
	[PB_Y+1_M7] [int] NULL,
	[PB_Y+1_M8] [int] NULL,
	[PB_Y+1_M9] [int] NULL,
	[PB_Y+1_M10] [int] NULL,
	[PB_Y+1_M11] [int] NULL,
	[PB_Y+1_M12] [int] NULL,
	[T1_Y0_M1] [int] NULL,
	[T1_Y0_M2] [int] NULL,
	[T1_Y0_M3] [int] NULL,
	[T1_Y0_M4] [int] NULL,
	[T1_Y0_M5] [int] NULL,
	[T1_Y0_M6] [int] NULL,
	[T1_Y0_M7] [int] NULL,
	[T1_Y0_M8] [int] NULL,
	[T1_Y0_M9] [int] NULL,
	[T1_Y0_M10] [int] NULL,
	[T1_Y0_M11] [int] NULL,
	[T1_Y0_M12] [int] NULL,
	[T2_Y0_M1] [int] NULL,
	[T2_Y0_M2] [int] NULL,
	[T2_Y0_M3] [int] NULL,
	[T2_Y0_M4] [int] NULL,
	[T2_Y0_M5] [int] NULL,
	[T2_Y0_M6] [int] NULL,
	[T2_Y0_M7] [int] NULL,
	[T2_Y0_M8] [int] NULL,
	[T2_Y0_M9] [int] NULL,
	[T2_Y0_M10] [int] NULL,
	[T2_Y0_M11] [int] NULL,
	[T2_Y0_M12] [int] NULL,
	[T3_Y0_M1] [int] NULL,
	[T3_Y0_M2] [int] NULL,
	[T3_Y0_M3] [int] NULL,
	[T3_Y0_M4] [int] NULL,
	[T3_Y0_M5] [int] NULL,
	[T3_Y0_M6] [int] NULL,
	[T3_Y0_M7] [int] NULL,
	[T3_Y0_M8] [int] NULL,
	[T3_Y0_M9] [int] NULL,
	[T3_Y0_M10] [int] NULL,
	[T3_Y0_M11] [int] NULL,
	[T3_Y0_M12] [int] NULL,
	[(Value)_Y-2 (u) M1] [numeric](18, 0) NULL,
	[(Value)_Y-2 (u) M2] [numeric](18, 0) NULL,
	[(Value)_Y-2 (u) M3] [numeric](18, 0) NULL,
	[(Value)_Y-2 (u) M4] [numeric](18, 0) NULL,
	[(Value)_Y-2 (u) M5] [numeric](18, 0) NULL,
	[(Value)_Y-2 (u) M6] [numeric](18, 0) NULL,
	[(Value)_Y-2 (u) M7] [numeric](18, 0) NULL,
	[(Value)_Y-2 (u) M8] [numeric](18, 0) NULL,
	[(Value)_Y-2 (u) M9] [numeric](18, 0) NULL,
	[(Value)_Y-2 (u) M10] [numeric](18, 0) NULL,
	[(Value)_Y-2 (u) M11] [numeric](18, 0) NULL,
	[(Value)_Y-2 (u) M12] [numeric](18, 0) NULL,
	[(Value)_Y-1 (u) M1] [numeric](18, 0) NULL,
	[(Value)_Y-1 (u) M2] [numeric](18, 0) NULL,
	[(Value)_Y-1 (u) M3] [numeric](18, 0) NULL,
	[(Value)_Y-1 (u) M4] [numeric](18, 0) NULL,
	[(Value)_Y-1 (u) M5] [numeric](18, 0) NULL,
	[(Value)_Y-1 (u) M6] [numeric](18, 0) NULL,
	[(Value)_Y-1 (u) M7] [numeric](18, 0) NULL,
	[(Value)_Y-1 (u) M8] [numeric](18, 0) NULL,
	[(Value)_Y-1 (u) M9] [numeric](18, 0) NULL,
	[(Value)_Y-1 (u) M10] [numeric](18, 0) NULL,
	[(Value)_Y-1 (u) M11] [numeric](18, 0) NULL,
	[(Value)_Y-1 (u) M12] [numeric](18, 0) NULL,
	[(Value)_Y0 (u) M1] [numeric](18, 0) NULL,
	[(Value)_Y0 (u) M2] [numeric](18, 0) NULL,
	[(Value)_Y0 (u) M3] [numeric](18, 0) NULL,
	[(Value)_Y0 (u) M4] [numeric](18, 0) NULL,
	[(Value)_Y0 (u) M5] [numeric](18, 0) NULL,
	[(Value)_Y0 (u) M6] [numeric](18, 0) NULL,
	[(Value)_Y0 (u) M7] [numeric](18, 0) NULL,
	[(Value)_Y0 (u) M8] [numeric](18, 0) NULL,
	[(Value)_Y0 (u) M9] [numeric](18, 0) NULL,
	[(Value)_Y0 (u) M10] [numeric](18, 0) NULL,
	[(Value)_Y0 (u) M11] [numeric](18, 0) NULL,
	[(Value)_Y0 (u) M12] [numeric](18, 0) NULL,
	[(Value)_Y+1 (u) M1] [numeric](18, 0) NULL,
	[(Value)_Y+1 (u) M2] [numeric](18, 0) NULL,
	[(Value)_Y+1 (u) M3] [numeric](18, 0) NULL,
	[(Value)_Y+1 (u) M4] [numeric](18, 0) NULL,
	[(Value)_Y+1 (u) M5] [numeric](18, 0) NULL,
	[(Value)_Y+1 (u) M6] [numeric](18, 0) NULL,
	[(Value)_Y+1 (u) M7] [numeric](18, 0) NULL,
	[(Value)_Y+1 (u) M8] [numeric](18, 0) NULL,
	[(Value)_Y+1 (u) M9] [numeric](18, 0) NULL,
	[(Value)_Y+1 (u) M10] [numeric](18, 0) NULL,
	[(Value)_Y+1 (u) M11] [numeric](18, 0) NULL,
	[(Value)_Y+1 (u) M12] [numeric](18, 0) NULL,
	[(Value)_(m-1)_Y0 (u) M1] [numeric](18, 0) NULL,
	[(Value)_(m-1)_Y0 (u) M2] [numeric](18, 0) NULL,
	[(Value)_(m-1)_Y0 (u) M3] [numeric](18, 0) NULL,
	[(Value)_(m-1)_Y0 (u) M4] [numeric](18, 0) NULL,
	[(Value)_(m-1)_Y0 (u) M5] [numeric](18, 0) NULL,
	[(Value)_(m-1)_Y0 (u) M6] [numeric](18, 0) NULL,
	[(Value)_(m-1)_Y0 (u) M7] [numeric](18, 0) NULL,
	[(Value)_(m-1)_Y0 (u) M8] [numeric](18, 0) NULL,
	[(Value)_(m-1)_Y0 (u) M9] [numeric](18, 0) NULL,
	[(Value)_(m-1)_Y0 (u) M10] [numeric](18, 0) NULL,
	[(Value)_(m-1)_Y0 (u) M11] [numeric](18, 0) NULL,
	[(Value)_(m-1)_Y0 (u) M12] [numeric](18, 0) NULL,
	[(Value)_(m-1)_Y+1 (u) M1] [numeric](18, 0) NULL,
	[(Value)_(m-1)_Y+1 (u) M2] [numeric](18, 0) NULL,
	[(Value)_(m-1)_Y+1 (u) M3] [numeric](18, 0) NULL,
	[(Value)_(m-1)_Y+1 (u) M4] [numeric](18, 0) NULL,
	[(Value)_(m-1)_Y+1 (u) M5] [numeric](18, 0) NULL,
	[(Value)_(m-1)_Y+1 (u) M6] [numeric](18, 0) NULL,
	[(Value)_(m-1)_Y+1 (u) M7] [numeric](18, 0) NULL,
	[(Value)_(m-1)_Y+1 (u) M8] [numeric](18, 0) NULL,
	[(Value)_(m-1)_Y+1 (u) M9] [numeric](18, 0) NULL,
	[(Value)_(m-1)_Y+1 (u) M10] [numeric](18, 0) NULL,
	[(Value)_(m-1)_Y+1 (u) M11] [numeric](18, 0) NULL,
	[(Value)_(m-1)_Y+1 (u) M12] [numeric](18, 0) NULL,
	[(Value)_B_Y0_M1] [numeric](18, 0) NULL,
	[(Value)_B_Y0_M2] [numeric](18, 0) NULL,
	[(Value)_B_Y0_M3] [numeric](18, 0) NULL,
	[(Value)_B_Y0_M4] [numeric](18, 0) NULL,
	[(Value)_B_Y0_M5] [numeric](18, 0) NULL,
	[(Value)_B_Y0_M6] [numeric](18, 0) NULL,
	[(Value)_B_Y0_M7] [numeric](18, 0) NULL,
	[(Value)_B_Y0_M8] [numeric](18, 0) NULL,
	[(Value)_B_Y0_M9] [numeric](18, 0) NULL,
	[(Value)_B_Y0_M10] [numeric](18, 0) NULL,
	[(Value)_B_Y0_M11] [numeric](18, 0) NULL,
	[(Value)_B_Y0_M12] [numeric](18, 0) NULL,
	[(Value)_B_Y+1_M1] [numeric](18, 0) NULL,
	[(Value)_B_Y+1_M2] [numeric](18, 0) NULL,
	[(Value)_B_Y+1_M3] [numeric](18, 0) NULL,
	[(Value)_B_Y+1_M4] [numeric](18, 0) NULL,
	[(Value)_B_Y+1_M5] [numeric](18, 0) NULL,
	[(Value)_B_Y+1_M6] [numeric](18, 0) NULL,
	[(Value)_B_Y+1_M7] [numeric](18, 0) NULL,
	[(Value)_B_Y+1_M8] [numeric](18, 0) NULL,
	[(Value)_B_Y+1_M9] [numeric](18, 0) NULL,
	[(Value)_B_Y+1_M10] [numeric](18, 0) NULL,
	[(Value)_B_Y+1_M11] [numeric](18, 0) NULL,
	[(Value)_B_Y+1_M12] [numeric](18, 0) NULL,
	[(Value)_PB_Y+1_M1] [numeric](18, 0) NULL,
	[(Value)_PB_Y+1_M2] [numeric](18, 0) NULL,
	[(Value)_PB_Y+1_M3] [numeric](18, 0) NULL,
	[(Value)_PB_Y+1_M4] [numeric](18, 0) NULL,
	[(Value)_PB_Y+1_M5] [numeric](18, 0) NULL,
	[(Value)_PB_Y+1_M6] [numeric](18, 0) NULL,
	[(Value)_PB_Y+1_M7] [numeric](18, 0) NULL,
	[(Value)_PB_Y+1_M8] [numeric](18, 0) NULL,
	[(Value)_PB_Y+1_M9] [numeric](18, 0) NULL,
	[(Value)_PB_Y+1_M10] [numeric](18, 0) NULL,
	[(Value)_PB_Y+1_M11] [numeric](18, 0) NULL,
	[(Value)_PB_Y+1_M12] [numeric](18, 0) NULL,
	[(Value)_T1_Y0_M1] [numeric](18, 0) NULL,
	[(Value)_T1_Y0_M2] [numeric](18, 0) NULL,
	[(Value)_T1_Y0_M3] [numeric](18, 0) NULL,
	[(Value)_T1_Y0_M4] [numeric](18, 0) NULL,
	[(Value)_T1_Y0_M5] [numeric](18, 0) NULL,
	[(Value)_T1_Y0_M6] [numeric](18, 0) NULL,
	[(Value)_T1_Y0_M7] [numeric](18, 0) NULL,
	[(Value)_T1_Y0_M8] [numeric](18, 0) NULL,
	[(Value)_T1_Y0_M9] [numeric](18, 0) NULL,
	[(Value)_T1_Y0_M10] [numeric](18, 0) NULL,
	[(Value)_T1_Y0_M11] [numeric](18, 0) NULL,
	[(Value)_T1_Y0_M12] [numeric](18, 0) NULL,
	[(Value)_T2_Y0_M1] [numeric](18, 0) NULL,
	[(Value)_T2_Y0_M2] [numeric](18, 0) NULL,
	[(Value)_T2_Y0_M3] [numeric](18, 0) NULL,
	[(Value)_T2_Y0_M4] [numeric](18, 0) NULL,
	[(Value)_T2_Y0_M5] [numeric](18, 0) NULL,
	[(Value)_T2_Y0_M6] [numeric](18, 0) NULL,
	[(Value)_T2_Y0_M7] [numeric](18, 0) NULL,
	[(Value)_T2_Y0_M8] [numeric](18, 0) NULL,
	[(Value)_T2_Y0_M9] [numeric](18, 0) NULL,
	[(Value)_T2_Y0_M10] [numeric](18, 0) NULL,
	[(Value)_T2_Y0_M11] [numeric](18, 0) NULL,
	[(Value)_T2_Y0_M12] [numeric](18, 0) NULL,
	[(Value)_T3_Y0_M1] [numeric](18, 0) NULL,
	[(Value)_T3_Y0_M2] [numeric](18, 0) NULL,
	[(Value)_T3_Y0_M3] [numeric](18, 0) NULL,
	[(Value)_T3_Y0_M4] [numeric](18, 0) NULL,
	[(Value)_T3_Y0_M5] [numeric](18, 0) NULL,
	[(Value)_T3_Y0_M6] [numeric](18, 0) NULL,
	[(Value)_T3_Y0_M7] [numeric](18, 0) NULL,
	[(Value)_T3_Y0_M8] [numeric](18, 0) NULL,
	[(Value)_T3_Y0_M9] [numeric](18, 0) NULL,
	[(Value)_T3_Y0_M10] [numeric](18, 0) NULL,
	[(Value)_T3_Y0_M11] [numeric](18, 0) NULL,
	[(Value)_T3_Y0_M12] [numeric](18, 0) NULL
)
with encryption
As
begin
	declare 
		--@division		nvarchar(3) = 'LLD',
		--@UVType			NVARCHAR(10) = 'U',--//U/V 
		--@Signature		NVARCHAR(50) = '', 
		--@Caterogy		NVARCHAR(50) = '', -->Select All = ''	
		--@SubCat			NVARCHAR(50) = '', -->Select All = ''
		--@Channel		NVARCHAR(20) = 'O+O', 
		--@SubGroup		NVARCHAR(50) = '', -->Select All = ''
		--@SubGroupBP		NVARCHAR(50) = '',-->Select All = ''
		--@Hero			nvarchar(100) = '',-->Select All = ''
		@sql			nvarchar(max) = '',
		@sql1			nvarchar(max) = '',
		@sql2			nvarchar(max) = '',
		@debug			int = 0

	if @division = 'CPD'
	begin
		INSERT INTO @tmp
		select
			[SO Forecasting lines] = o.[Forecasting lines],	
			f.[Product type],
			f.[Signature],
			f.[CAT/Axe],
			f.[SUB CAT/ Sub Axe],
			f.[GROUP/ Class],
			f.[Ref. Code],
			f.[SUB GROUP/ Brand],
			f.[HERO],
			f.[Channel],
			f.[Product status],
			f.[Time series],
			f.[SIT],
			f.[SIT Day],
			f.[SOH],
			f.[MTD SI],
			f.[Total GIT],
			f.[GIT M0],
			f.[GIT M1],
			f.[GIT M2],
			f.[GIT M3],
			f.[AVE P3M Y-1],
			f.[AVE F3M Y-1],
			f.[AVE P3M Y0],
			f.[AVE F3M Y0],
			f.[%F3M Y0/ P3M Y0],
			f.[%F3M Y-1/ P3M Y-1],
			f.[SLOB],
			f.[Y-2 (u) M1],
			f.[Y-2 (u) M2],
			f.[Y-2 (u) M3],
			f.[Y-2 (u) M4],
			f.[Y-2 (u) M5],
			f.[Y-2 (u) M6],
			f.[Y-2 (u) M7],
			f.[Y-2 (u) M8],
			f.[Y-2 (u) M9],
			f.[Y-2 (u) M10],
			f.[Y-2 (u) M11],
			f.[Y-2 (u) M12],
			f.[Y-1 (u) M1],
			f.[Y-1 (u) M2],
			f.[Y-1 (u) M3],
			f.[Y-1 (u) M4],
			f.[Y-1 (u) M5],
			f.[Y-1 (u) M6],
			f.[Y-1 (u) M7],
			f.[Y-1 (u) M8],
			f.[Y-1 (u) M9],
			f.[Y-1 (u) M10],
			f.[Y-1 (u) M11],
			f.[Y-1 (u) M12],
			f.[Y0 (u) M1],
			f.[Y0 (u) M2],
			f.[Y0 (u) M3],
			f.[Y0 (u) M4],
			f.[Y0 (u) M5],
			f.[Y0 (u) M6],
			f.[Y0 (u) M7],
			f.[Y0 (u) M8],
			f.[Y0 (u) M9],
			f.[Y0 (u) M10],
			f.[Y0 (u) M11],
			f.[Y0 (u) M12],
			f.[Y+1 (u) M1],
			f.[Y+1 (u) M2],
			f.[Y+1 (u) M3],
			f.[Y+1 (u) M4],
			f.[Y+1 (u) M5],
			f.[Y+1 (u) M6],
			f.[Y+1 (u) M7],
			f.[Y+1 (u) M8],
			f.[Y+1 (u) M9],
			f.[Y+1 (u) M10],
			f.[Y+1 (u) M11],
			f.[Y+1 (u) M12],
			f.[(m-1)_Y0 (u) M1],
			f.[(m-1)_Y0 (u) M2],
			f.[(m-1)_Y0 (u) M3],
			f.[(m-1)_Y0 (u) M4],
			f.[(m-1)_Y0 (u) M5],
			f.[(m-1)_Y0 (u) M6],
			f.[(m-1)_Y0 (u) M7],
			f.[(m-1)_Y0 (u) M8],
			f.[(m-1)_Y0 (u) M9],
			f.[(m-1)_Y0 (u) M10],
			f.[(m-1)_Y0 (u) M11],
			f.[(m-1)_Y0 (u) M12],
			f.[(m-1)_Y+1 (u) M1],
			f.[(m-1)_Y+1 (u) M2],
			f.[(m-1)_Y+1 (u) M3],
			f.[(m-1)_Y+1 (u) M4],
			f.[(m-1)_Y+1 (u) M5],
			f.[(m-1)_Y+1 (u) M6],
			f.[(m-1)_Y+1 (u) M7],
			f.[(m-1)_Y+1 (u) M8],
			f.[(m-1)_Y+1 (u) M9],
			f.[(m-1)_Y+1 (u) M10],
			f.[(m-1)_Y+1 (u) M11],
			f.[(m-1)_Y+1 (u) M12],
			f.[B_Y0_M1],
			f.[B_Y0_M2],
			f.[B_Y0_M3],
			f.[B_Y0_M4],
			f.[B_Y0_M5],
			f.[B_Y0_M6],
			f.[B_Y0_M7],
			f.[B_Y0_M8],
			f.[B_Y0_M9],
			f.[B_Y0_M10],
			f.[B_Y0_M11],
			f.[B_Y0_M12],
			f.[B_Y+1_M1],
			f.[B_Y+1_M2],
			f.[B_Y+1_M3],
			f.[B_Y+1_M4],
			f.[B_Y+1_M5],
			f.[B_Y+1_M6],
			f.[B_Y+1_M7],
			f.[B_Y+1_M8],
			f.[B_Y+1_M9],
			f.[B_Y+1_M10],
			f.[B_Y+1_M11],
			f.[B_Y+1_M12],
			f.[PB_Y+1_M1],
			f.[PB_Y+1_M2],
			f.[PB_Y+1_M3],
			f.[PB_Y+1_M4],
			f.[PB_Y+1_M5],
			f.[PB_Y+1_M6],
			f.[PB_Y+1_M7],
			f.[PB_Y+1_M8],
			f.[PB_Y+1_M9],
			f.[PB_Y+1_M10],
			f.[PB_Y+1_M11],
			f.[PB_Y+1_M12],
			f.[T1_Y0_M1],
			f.[T1_Y0_M2],
			f.[T1_Y0_M3],
			f.[T1_Y0_M4],
			f.[T1_Y0_M5],
			f.[T1_Y0_M6],
			f.[T1_Y0_M7],
			f.[T1_Y0_M8],
			f.[T1_Y0_M9],
			f.[T1_Y0_M10],
			f.[T1_Y0_M11],
			f.[T1_Y0_M12],
			f.[T2_Y0_M1],
			f.[T2_Y0_M2],
			f.[T2_Y0_M3],
			f.[T2_Y0_M4],
			f.[T2_Y0_M5],
			f.[T2_Y0_M6],
			f.[T2_Y0_M7],
			f.[T2_Y0_M8],
			f.[T2_Y0_M9],
			f.[T2_Y0_M10],
			f.[T2_Y0_M11],
			f.[T2_Y0_M12],
			f.[T3_Y0_M1],
			f.[T3_Y0_M2],
			f.[T3_Y0_M3],
			f.[T3_Y0_M4],
			f.[T3_Y0_M5],
			f.[T3_Y0_M6],
			f.[T3_Y0_M7],
			f.[T3_Y0_M8],
			f.[T3_Y0_M9],
			f.[T3_Y0_M10],
			f.[T3_Y0_M11],
			f.[T3_Y0_M12],
		--select @sql1 = '
			f.[(Value)_Y-2 (u) M1],
			f.[(Value)_Y-2 (u) M2],
			f.[(Value)_Y-2 (u) M3],
			f.[(Value)_Y-2 (u) M4],
			f.[(Value)_Y-2 (u) M5],
			f.[(Value)_Y-2 (u) M6],
			f.[(Value)_Y-2 (u) M7],
			f.[(Value)_Y-2 (u) M8],
			f.[(Value)_Y-2 (u) M9],
			f.[(Value)_Y-2 (u) M10],
			f.[(Value)_Y-2 (u) M11],
			f.[(Value)_Y-2 (u) M12],
			f.[(Value)_Y-1 (u) M1],
			f.[(Value)_Y-1 (u) M2],
			f.[(Value)_Y-1 (u) M3],
			f.[(Value)_Y-1 (u) M4],
			f.[(Value)_Y-1 (u) M5],
			f.[(Value)_Y-1 (u) M6],
			f.[(Value)_Y-1 (u) M7],
			f.[(Value)_Y-1 (u) M8],
			f.[(Value)_Y-1 (u) M9],
			f.[(Value)_Y-1 (u) M10],
			f.[(Value)_Y-1 (u) M11],
			f.[(Value)_Y-1 (u) M12],
			f.[(Value)_Y0 (u) M1],
			f.[(Value)_Y0 (u) M2],
			f.[(Value)_Y0 (u) M3],
			f.[(Value)_Y0 (u) M4],
			f.[(Value)_Y0 (u) M5],
			f.[(Value)_Y0 (u) M6],
			f.[(Value)_Y0 (u) M7],
			f.[(Value)_Y0 (u) M8],
			f.[(Value)_Y0 (u) M9],
			f.[(Value)_Y0 (u) M10],
			f.[(Value)_Y0 (u) M11],
			f.[(Value)_Y0 (u) M12],
			f.[(Value)_Y+1 (u) M1],
			f.[(Value)_Y+1 (u) M2],
			f.[(Value)_Y+1 (u) M3],
			f.[(Value)_Y+1 (u) M4],
			f.[(Value)_Y+1 (u) M5],
			f.[(Value)_Y+1 (u) M6],
			f.[(Value)_Y+1 (u) M7],
			f.[(Value)_Y+1 (u) M8],
			f.[(Value)_Y+1 (u) M9],
			f.[(Value)_Y+1 (u) M10],
			f.[(Value)_Y+1 (u) M11],
			f.[(Value)_Y+1 (u) M12],
			f.[(Value)_(m-1)_Y0 (u) M1],
			f.[(Value)_(m-1)_Y0 (u) M2],
			f.[(Value)_(m-1)_Y0 (u) M3],
			f.[(Value)_(m-1)_Y0 (u) M4],
			f.[(Value)_(m-1)_Y0 (u) M5],
			f.[(Value)_(m-1)_Y0 (u) M6],
			f.[(Value)_(m-1)_Y0 (u) M7],
			f.[(Value)_(m-1)_Y0 (u) M8],
			f.[(Value)_(m-1)_Y0 (u) M9],
			f.[(Value)_(m-1)_Y0 (u) M10],
			f.[(Value)_(m-1)_Y0 (u) M11],
			f.[(Value)_(m-1)_Y0 (u) M12],
			f.[(Value)_(m-1)_Y+1 (u) M1],
			f.[(Value)_(m-1)_Y+1 (u) M2],
			f.[(Value)_(m-1)_Y+1 (u) M3],
			f.[(Value)_(m-1)_Y+1 (u) M4],
			f.[(Value)_(m-1)_Y+1 (u) M5],
			f.[(Value)_(m-1)_Y+1 (u) M6],
			f.[(Value)_(m-1)_Y+1 (u) M7],
			f.[(Value)_(m-1)_Y+1 (u) M8],
			f.[(Value)_(m-1)_Y+1 (u) M9],
			f.[(Value)_(m-1)_Y+1 (u) M10],
			f.[(Value)_(m-1)_Y+1 (u) M11],
			f.[(Value)_(m-1)_Y+1 (u) M12],
			f.[(Value)_B_Y0_M1],
			f.[(Value)_B_Y0_M2],
			f.[(Value)_B_Y0_M3],
			f.[(Value)_B_Y0_M4],
			f.[(Value)_B_Y0_M5],
			f.[(Value)_B_Y0_M6],
			f.[(Value)_B_Y0_M7],
			f.[(Value)_B_Y0_M8],
			f.[(Value)_B_Y0_M9],
			f.[(Value)_B_Y0_M10],
			f.[(Value)_B_Y0_M11],
			f.[(Value)_B_Y0_M12],
			f.[(Value)_B_Y+1_M1],
			f.[(Value)_B_Y+1_M2],
			f.[(Value)_B_Y+1_M3],
			f.[(Value)_B_Y+1_M4],
			f.[(Value)_B_Y+1_M5],
			f.[(Value)_B_Y+1_M6],
			f.[(Value)_B_Y+1_M7],
			f.[(Value)_B_Y+1_M8],
			f.[(Value)_B_Y+1_M9],
			f.[(Value)_B_Y+1_M10],
			f.[(Value)_B_Y+1_M11],
			f.[(Value)_B_Y+1_M12],
			f.[(Value)_PB_Y+1_M1],
			f.[(Value)_PB_Y+1_M2],
			f.[(Value)_PB_Y+1_M3],
			f.[(Value)_PB_Y+1_M4],
			f.[(Value)_PB_Y+1_M5],
			f.[(Value)_PB_Y+1_M6],
			f.[(Value)_PB_Y+1_M7],
			f.[(Value)_PB_Y+1_M8],
			f.[(Value)_PB_Y+1_M9],
			f.[(Value)_PB_Y+1_M10],
			f.[(Value)_PB_Y+1_M11],
			f.[(Value)_PB_Y+1_M12],
			f.[(Value)_T1_Y0_M1],
			f.[(Value)_T1_Y0_M2],
			f.[(Value)_T1_Y0_M3],
			f.[(Value)_T1_Y0_M4],
			f.[(Value)_T1_Y0_M5],
			f.[(Value)_T1_Y0_M6],
			f.[(Value)_T1_Y0_M7],
			f.[(Value)_T1_Y0_M8],
			f.[(Value)_T1_Y0_M9],
			f.[(Value)_T1_Y0_M10],
			f.[(Value)_T1_Y0_M11],
			f.[(Value)_T1_Y0_M12], 
		--select @sql2 = '
			f.[(Value)_T2_Y0_M1],
			f.[(Value)_T2_Y0_M2],
			f.[(Value)_T2_Y0_M3],
			f.[(Value)_T2_Y0_M4],
			f.[(Value)_T2_Y0_M5],
			f.[(Value)_T2_Y0_M6],
			f.[(Value)_T2_Y0_M7],
			f.[(Value)_T2_Y0_M8],
			f.[(Value)_T2_Y0_M9],
			f.[(Value)_T2_Y0_M10],
			f.[(Value)_T2_Y0_M11],
			f.[(Value)_T2_Y0_M12],
			f.[(Value)_T3_Y0_M1],
			f.[(Value)_T3_Y0_M2],
			f.[(Value)_T3_Y0_M3],
			f.[(Value)_T3_Y0_M4],
			f.[(Value)_T3_Y0_M5],
			f.[(Value)_T3_Y0_M6],
			f.[(Value)_T3_Y0_M7],
			f.[(Value)_T3_Y0_M8],
			f.[(Value)_T3_Y0_M9],
			f.[(Value)_T3_Y0_M10],
			f.[(Value)_T3_Y0_M11],
			f.[(Value)_T3_Y0_M12]
		from FC_FM_Original_CPD f (NOLOCK)
		Left join
		(
			select DISTINCT
				[Forecasting lines],
				[SUB GROUP/ Brand]
			from fnc_FC_SO_OPTIMUS_MAPPING_SUBGRP(@division)
		) as o on o.[SUB GROUP/ Brand] = f.[SUB GROUP/ Brand]
		where 
				(len(@Signature) = 0 OR f.[Signature] =@Signature)
			and (len(@Caterogy)=0 OR f.[CAT/Axe] = @Caterogy)
			and (len(@SubCat)=0 OR f.[SUB CAT/ Sub Axe] = @SubCat)
			and (len(@Channel)=0 OR f.Channel = @Channel)
			and (len(@SubGroup)=0 OR f.[SUB GROUP/ Brand] = @SubGroup)
			and (len(@Hero)=0 OR f.HERO = @Hero)
			and (len(@SubGroupBP)=0 OR o.[Forecasting lines] = @SubGroupBP) 
	end
	else if @division = 'LLD'
	begin
		INSERT INTO @tmp
		select
			[SO Forecasting lines] = o.[Forecasting lines],	
			f.[Product type],
			f.[Signature],
			f.[CAT/Axe],
			f.[SUB CAT/ Sub Axe],
			f.[GROUP/ Class],
			f.[Ref. Code],
			f.[SUB GROUP/ Brand],
			f.[HERO],
			f.[Channel],
			f.[Product status],
			f.[Time series],
			f.[SIT],
			f.[SIT Day],
			f.[SOH],
			f.[MTD SI],
			f.[Total GIT],
			f.[GIT M0],
			f.[GIT M1],
			f.[GIT M2],
			f.[GIT M3],
			f.[AVE P3M Y-1],
			f.[AVE F3M Y-1],
			f.[AVE P3M Y0],
			f.[AVE F3M Y0],
			f.[%F3M Y0/ P3M Y0],
			f.[%F3M Y-1/ P3M Y-1],
			f.[SLOB],
			f.[Y-2 (u) M1],
			f.[Y-2 (u) M2],
			f.[Y-2 (u) M3],
			f.[Y-2 (u) M4],
			f.[Y-2 (u) M5],
			f.[Y-2 (u) M6],
			f.[Y-2 (u) M7],
			f.[Y-2 (u) M8],
			f.[Y-2 (u) M9],
			f.[Y-2 (u) M10],
			f.[Y-2 (u) M11],
			f.[Y-2 (u) M12],
			f.[Y-1 (u) M1],
			f.[Y-1 (u) M2],
			f.[Y-1 (u) M3],
			f.[Y-1 (u) M4],
			f.[Y-1 (u) M5],
			f.[Y-1 (u) M6],
			f.[Y-1 (u) M7],
			f.[Y-1 (u) M8],
			f.[Y-1 (u) M9],
			f.[Y-1 (u) M10],
			f.[Y-1 (u) M11],
			f.[Y-1 (u) M12],
			f.[Y0 (u) M1],
			f.[Y0 (u) M2],
			f.[Y0 (u) M3],
			f.[Y0 (u) M4],
			f.[Y0 (u) M5],
			f.[Y0 (u) M6],
			f.[Y0 (u) M7],
			f.[Y0 (u) M8],
			f.[Y0 (u) M9],
			f.[Y0 (u) M10],
			f.[Y0 (u) M11],
			f.[Y0 (u) M12],
			f.[Y+1 (u) M1],
			f.[Y+1 (u) M2],
			f.[Y+1 (u) M3],
			f.[Y+1 (u) M4],
			f.[Y+1 (u) M5],
			f.[Y+1 (u) M6],
			f.[Y+1 (u) M7],
			f.[Y+1 (u) M8],
			f.[Y+1 (u) M9],
			f.[Y+1 (u) M10],
			f.[Y+1 (u) M11],
			f.[Y+1 (u) M12],
			f.[(m-1)_Y0 (u) M1],
			f.[(m-1)_Y0 (u) M2],
			f.[(m-1)_Y0 (u) M3],
			f.[(m-1)_Y0 (u) M4],
			f.[(m-1)_Y0 (u) M5],
			f.[(m-1)_Y0 (u) M6],
			f.[(m-1)_Y0 (u) M7],
			f.[(m-1)_Y0 (u) M8],
			f.[(m-1)_Y0 (u) M9],
			f.[(m-1)_Y0 (u) M10],
			f.[(m-1)_Y0 (u) M11],
			f.[(m-1)_Y0 (u) M12],
			f.[(m-1)_Y+1 (u) M1],
			f.[(m-1)_Y+1 (u) M2],
			f.[(m-1)_Y+1 (u) M3],
			f.[(m-1)_Y+1 (u) M4],
			f.[(m-1)_Y+1 (u) M5],
			f.[(m-1)_Y+1 (u) M6],
			f.[(m-1)_Y+1 (u) M7],
			f.[(m-1)_Y+1 (u) M8],
			f.[(m-1)_Y+1 (u) M9],
			f.[(m-1)_Y+1 (u) M10],
			f.[(m-1)_Y+1 (u) M11],
			f.[(m-1)_Y+1 (u) M12],
			f.[B_Y0_M1],
			f.[B_Y0_M2],
			f.[B_Y0_M3],
			f.[B_Y0_M4],
			f.[B_Y0_M5],
			f.[B_Y0_M6],
			f.[B_Y0_M7],
			f.[B_Y0_M8],
			f.[B_Y0_M9],
			f.[B_Y0_M10],
			f.[B_Y0_M11],
			f.[B_Y0_M12],
			f.[B_Y+1_M1],
			f.[B_Y+1_M2],
			f.[B_Y+1_M3],
			f.[B_Y+1_M4],
			f.[B_Y+1_M5],
			f.[B_Y+1_M6],
			f.[B_Y+1_M7],
			f.[B_Y+1_M8],
			f.[B_Y+1_M9],
			f.[B_Y+1_M10],
			f.[B_Y+1_M11],
			f.[B_Y+1_M12],
			f.[PB_Y+1_M1],
			f.[PB_Y+1_M2],
			f.[PB_Y+1_M3],
			f.[PB_Y+1_M4],
			f.[PB_Y+1_M5],
			f.[PB_Y+1_M6],
			f.[PB_Y+1_M7],
			f.[PB_Y+1_M8],
			f.[PB_Y+1_M9],
			f.[PB_Y+1_M10],
			f.[PB_Y+1_M11],
			f.[PB_Y+1_M12],
			f.[T1_Y0_M1],
			f.[T1_Y0_M2],
			f.[T1_Y0_M3],
			f.[T1_Y0_M4],
			f.[T1_Y0_M5],
			f.[T1_Y0_M6],
			f.[T1_Y0_M7],
			f.[T1_Y0_M8],
			f.[T1_Y0_M9],
			f.[T1_Y0_M10],
			f.[T1_Y0_M11],
			f.[T1_Y0_M12],
			f.[T2_Y0_M1],
			f.[T2_Y0_M2],
			f.[T2_Y0_M3],
			f.[T2_Y0_M4],
			f.[T2_Y0_M5],
			f.[T2_Y0_M6],
			f.[T2_Y0_M7],
			f.[T2_Y0_M8],
			f.[T2_Y0_M9],
			f.[T2_Y0_M10],
			f.[T2_Y0_M11],
			f.[T2_Y0_M12],
			f.[T3_Y0_M1],
			f.[T3_Y0_M2],
			f.[T3_Y0_M3],
			f.[T3_Y0_M4],
			f.[T3_Y0_M5],
			f.[T3_Y0_M6],
			f.[T3_Y0_M7],
			f.[T3_Y0_M8],
			f.[T3_Y0_M9],
			f.[T3_Y0_M10],
			f.[T3_Y0_M11],
			f.[T3_Y0_M12],
		--select @sql1 = '
			f.[(Value)_Y-2 (u) M1],
			f.[(Value)_Y-2 (u) M2],
			f.[(Value)_Y-2 (u) M3],
			f.[(Value)_Y-2 (u) M4],
			f.[(Value)_Y-2 (u) M5],
			f.[(Value)_Y-2 (u) M6],
			f.[(Value)_Y-2 (u) M7],
			f.[(Value)_Y-2 (u) M8],
			f.[(Value)_Y-2 (u) M9],
			f.[(Value)_Y-2 (u) M10],
			f.[(Value)_Y-2 (u) M11],
			f.[(Value)_Y-2 (u) M12],
			f.[(Value)_Y-1 (u) M1],
			f.[(Value)_Y-1 (u) M2],
			f.[(Value)_Y-1 (u) M3],
			f.[(Value)_Y-1 (u) M4],
			f.[(Value)_Y-1 (u) M5],
			f.[(Value)_Y-1 (u) M6],
			f.[(Value)_Y-1 (u) M7],
			f.[(Value)_Y-1 (u) M8],
			f.[(Value)_Y-1 (u) M9],
			f.[(Value)_Y-1 (u) M10],
			f.[(Value)_Y-1 (u) M11],
			f.[(Value)_Y-1 (u) M12],
			f.[(Value)_Y0 (u) M1],
			f.[(Value)_Y0 (u) M2],
			f.[(Value)_Y0 (u) M3],
			f.[(Value)_Y0 (u) M4],
			f.[(Value)_Y0 (u) M5],
			f.[(Value)_Y0 (u) M6],
			f.[(Value)_Y0 (u) M7],
			f.[(Value)_Y0 (u) M8],
			f.[(Value)_Y0 (u) M9],
			f.[(Value)_Y0 (u) M10],
			f.[(Value)_Y0 (u) M11],
			f.[(Value)_Y0 (u) M12],
			f.[(Value)_Y+1 (u) M1],
			f.[(Value)_Y+1 (u) M2],
			f.[(Value)_Y+1 (u) M3],
			f.[(Value)_Y+1 (u) M4],
			f.[(Value)_Y+1 (u) M5],
			f.[(Value)_Y+1 (u) M6],
			f.[(Value)_Y+1 (u) M7],
			f.[(Value)_Y+1 (u) M8],
			f.[(Value)_Y+1 (u) M9],
			f.[(Value)_Y+1 (u) M10],
			f.[(Value)_Y+1 (u) M11],
			f.[(Value)_Y+1 (u) M12],
			f.[(Value)_(m-1)_Y0 (u) M1],
			f.[(Value)_(m-1)_Y0 (u) M2],
			f.[(Value)_(m-1)_Y0 (u) M3],
			f.[(Value)_(m-1)_Y0 (u) M4],
			f.[(Value)_(m-1)_Y0 (u) M5],
			f.[(Value)_(m-1)_Y0 (u) M6],
			f.[(Value)_(m-1)_Y0 (u) M7],
			f.[(Value)_(m-1)_Y0 (u) M8],
			f.[(Value)_(m-1)_Y0 (u) M9],
			f.[(Value)_(m-1)_Y0 (u) M10],
			f.[(Value)_(m-1)_Y0 (u) M11],
			f.[(Value)_(m-1)_Y0 (u) M12],
			f.[(Value)_(m-1)_Y+1 (u) M1],
			f.[(Value)_(m-1)_Y+1 (u) M2],
			f.[(Value)_(m-1)_Y+1 (u) M3],
			f.[(Value)_(m-1)_Y+1 (u) M4],
			f.[(Value)_(m-1)_Y+1 (u) M5],
			f.[(Value)_(m-1)_Y+1 (u) M6],
			f.[(Value)_(m-1)_Y+1 (u) M7],
			f.[(Value)_(m-1)_Y+1 (u) M8],
			f.[(Value)_(m-1)_Y+1 (u) M9],
			f.[(Value)_(m-1)_Y+1 (u) M10],
			f.[(Value)_(m-1)_Y+1 (u) M11],
			f.[(Value)_(m-1)_Y+1 (u) M12],
			f.[(Value)_B_Y0_M1],
			f.[(Value)_B_Y0_M2],
			f.[(Value)_B_Y0_M3],
			f.[(Value)_B_Y0_M4],
			f.[(Value)_B_Y0_M5],
			f.[(Value)_B_Y0_M6],
			f.[(Value)_B_Y0_M7],
			f.[(Value)_B_Y0_M8],
			f.[(Value)_B_Y0_M9],
			f.[(Value)_B_Y0_M10],
			f.[(Value)_B_Y0_M11],
			f.[(Value)_B_Y0_M12],
			f.[(Value)_B_Y+1_M1],
			f.[(Value)_B_Y+1_M2],
			f.[(Value)_B_Y+1_M3],
			f.[(Value)_B_Y+1_M4],
			f.[(Value)_B_Y+1_M5],
			f.[(Value)_B_Y+1_M6],
			f.[(Value)_B_Y+1_M7],
			f.[(Value)_B_Y+1_M8],
			f.[(Value)_B_Y+1_M9],
			f.[(Value)_B_Y+1_M10],
			f.[(Value)_B_Y+1_M11],
			f.[(Value)_B_Y+1_M12],
			f.[(Value)_PB_Y+1_M1],
			f.[(Value)_PB_Y+1_M2],
			f.[(Value)_PB_Y+1_M3],
			f.[(Value)_PB_Y+1_M4],
			f.[(Value)_PB_Y+1_M5],
			f.[(Value)_PB_Y+1_M6],
			f.[(Value)_PB_Y+1_M7],
			f.[(Value)_PB_Y+1_M8],
			f.[(Value)_PB_Y+1_M9],
			f.[(Value)_PB_Y+1_M10],
			f.[(Value)_PB_Y+1_M11],
			f.[(Value)_PB_Y+1_M12],
			f.[(Value)_T1_Y0_M1],
			f.[(Value)_T1_Y0_M2],
			f.[(Value)_T1_Y0_M3],
			f.[(Value)_T1_Y0_M4],
			f.[(Value)_T1_Y0_M5],
			f.[(Value)_T1_Y0_M6],
			f.[(Value)_T1_Y0_M7],
			f.[(Value)_T1_Y0_M8],
			f.[(Value)_T1_Y0_M9],
			f.[(Value)_T1_Y0_M10],
			f.[(Value)_T1_Y0_M11],
			f.[(Value)_T1_Y0_M12], 
		--select @sql2 = '
			f.[(Value)_T2_Y0_M1],
			f.[(Value)_T2_Y0_M2],
			f.[(Value)_T2_Y0_M3],
			f.[(Value)_T2_Y0_M4],
			f.[(Value)_T2_Y0_M5],
			f.[(Value)_T2_Y0_M6],
			f.[(Value)_T2_Y0_M7],
			f.[(Value)_T2_Y0_M8],
			f.[(Value)_T2_Y0_M9],
			f.[(Value)_T2_Y0_M10],
			f.[(Value)_T2_Y0_M11],
			f.[(Value)_T2_Y0_M12],
			f.[(Value)_T3_Y0_M1],
			f.[(Value)_T3_Y0_M2],
			f.[(Value)_T3_Y0_M3],
			f.[(Value)_T3_Y0_M4],
			f.[(Value)_T3_Y0_M5],
			f.[(Value)_T3_Y0_M6],
			f.[(Value)_T3_Y0_M7],
			f.[(Value)_T3_Y0_M8],
			f.[(Value)_T3_Y0_M9],
			f.[(Value)_T3_Y0_M10],
			f.[(Value)_T3_Y0_M11],
			f.[(Value)_T3_Y0_M12]
		from FC_FM_Original_LLD f (NOLOCK)
		Left join
		(
			select DISTINCT
				[Forecasting lines],
				[SUB GROUP/ Brand]
			from fnc_FC_SO_OPTIMUS_MAPPING_SUBGRP(@division)
		) as o on o.[SUB GROUP/ Brand] = f.[SUB GROUP/ Brand]
		where 
				(len(@Signature) = 0 OR f.[Signature] =@Signature)
			and (len(@Caterogy)=0 OR f.[CAT/Axe] = @Caterogy)
			and (len(@SubCat)=0 OR f.[SUB CAT/ Sub Axe] = @SubCat)
			and (len(@Channel)=0 OR f.Channel = @Channel)
			and (len(@SubGroup)=0 OR f.[SUB GROUP/ Brand] = @SubGroup)
			and (len(@Hero)=0 OR f.HERO = @Hero)
			and (len(@SubGroupBP)=0 OR o.[Forecasting lines] = @SubGroupBP) 
	end
	--execute(@sql+@sql1+@sql2)
	return
end
--select * from FC_FM_Original_CPD where HERO

/*
where 
			(len(@Signature) = 0 OR f.[Signature] =@Signature)
		and (len('''+@Caterogy+''')=0 OR f.[CAT/Axe] = '''+@Caterogy+''')
		and (len('''+@SubCat+''')=0 OR f.[SUB CAT/ Sub Axe] = '''+@SubCat+''')
		and (len('''+@Channel+''')=0 OR f.Channel = '''+@Channel+''')
		and (len('''+@SubGroup+''')=0 OR f.[SUB GROUP/ Brand] = '''+@SubGroup+''')
		and (len('''+@Hero+''')=0 OR f.HERO = '''+@Hero+''')
		and (len('''+@SubGroupBP+''')=0 OR o.[Forecasting lines] = '''+@SubGroupBP+''') '
*/