//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXCEL_ADDINS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.ACE.OLEDB.12.0;Data Source= C:\\phuongho\\PROJECT\\DESIGN\\CSharp\\" +
            "FC\\FC_Addins\\EXCEL_ADDINS\\bin\\Debug\\\\FC_SysData.mdb; Jet OLEDB:Database Password" +
            "=123")]
        public string AccessDB {
            get {
                return ((string)(this["AccessDB"]));
            }
            set {
                this["AccessDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5D636FD3-8106-4BE8-969D-44891479145C")]
        public string FC_Version_Guid {
            get {
                return ((string)(this["FC_Version_Guid"]));
            }
            set {
                this["FC_Version_Guid"] = value;
            }
        }
    }
}
