/*
	exec sp_create_View_FC_FM_Original 'LDB','202412'
	
	select * from V_FC_FM_Original_PPD_202412
*/

Alter proc sp_create_View_FC_FM_Original
	@division		nvarchar(3),
	@FM_KEY			nvarchar(6)
As
begin
	declare @debug		int=0
	declare @sql		varchar(max)=''
	declare @sql0		varchar(max)=''
	declare @sql00		varchar(max)=''
	declare @sql1		varchar(max)=''
	declare @sql2		varchar(max)=''
	declare @sql3		varchar(max)=''
	declare @sql4		varchar(max)=''
	declare @sql5		varchar(max)=''
	declare @sql6		varchar(max)=''
	declare @sql7		varchar(max)=''
	--declare @typeview	INT=1--0: new,1: old

	declare @ratio nvarchar(40)='*isnull(ff.[% Ratio]/100.0,1),0) as INT)'

	declare @view_name		nvarchar(200)=''
	select @view_name='V_FC_FM_Original_'+@division+'_'+@FM_KEY
	if @debug>0
	begin
		select @view_name '@view_name'
	end
	IF EXISTS(select * FROM sys.views where name =@view_name)
	BEGIN
		select @sql='drop view '+@view_name
		execute(@sql)
	end
	--select * from V_FC_CHANGE_FORECASTING_LINE_TYPE where [Division]='LLD' and changefc='1'
	if exists(select * from V_FC_CHANGE_FORECASTING_LINE_TYPE where [Division]=@division and changefc='1')
	begin
		select @sql0=
		'create view '+@view_name+'
		As
		Select DISTINCT
			[SO Forecasting lines]='''+case when @division='CPD' then '' else '[Forecasting lines]' end+''',
			f.[id],
			f.[Product type],
			f.[Signature],
			f.[CAT/Axe],
			f.[SUB CAT/ Sub Axe],
			f.[GROUP/ Class],
			f.[Ref. Code],
			[SUB GROUP/ Brand]=ff.[SUB GROUP/ Brand],
			f.[HERO],
			f.[Channel],
			f.[Product status],
			f.[Time series],
			[SIT]=cast(round(f.[SIT]'+@ratio+',
			[SIT Day]=cast(round(f.[SIT Day]'+@ratio+',
			[SOH]=cast(round(f.[SOH]'+@ratio+',
			[MTD SI]=cast(round(f.[MTD SI]'+@ratio+',
			[Total GIT]=cast(round(f.[Total GIT]'+@ratio+',
			[GIT M0]=cast(round(f.[GIT M0]'+@ratio+',
			[GIT M1]=cast(round(f.[GIT M1]'+@ratio+',
			[GIT M2]=cast(round(f.[GIT M2]'+@ratio+',
			[GIT M3]=cast(round(f.[GIT M3]'+@ratio+',
			[Risk (u) M0]=cast(round(f.[Risk (u) M0]'+@ratio+',
			[Risk (u) M1]=cast(round(f.[Risk (u) M1]'+@ratio+',
			[Risk (u) M2]=cast(round(f.[Risk (u) M2]'+@ratio+',
			[Risk (u) M3]=cast(round(f.[Risk (u) M3]'+@ratio+',
			[Total risk (u)]=cast(round(f.[Total risk (u)]'+@ratio+',
			[Risk (val) M0]=cast(round(f.[Risk (val) M0]'+@ratio+',
			[Risk (val) M1]=cast(round(f.[Risk (val) M1]'+@ratio+',
			[Risk (val) M2]=cast(round(f.[Risk (val) M2]'+@ratio+',
			[Risk (val) M3]=cast(round(f.[Risk (val) M3]'+@ratio+',
			[Total risk (val)]=cast(round(f.[Total risk (val)]'+@ratio+',
			[AVE P3M Y-1]=cast(round(f.[AVE P3M Y-1]'+@ratio+',
			[AVE F3M Y-1]=cast(round(f.[AVE F3M Y-1]'+@ratio+',
			[AVE P3M Y0]=cast(round(f.[AVE P3M Y0]'+@ratio+',
			[AVE F3M Y0]=cast(round(f.[AVE F3M Y0]'+@ratio+',
			[%F3M Y0/ P3M Y0]=cast(round(f.[%F3M Y0/ P3M Y0]'+@ratio+',
			[%F3M Y-1/ P3M Y-1]=cast(round(f.[%F3M Y-1/ P3M Y-1]'+@ratio+',
			[SLOB]=cast(round(f.[SLOB]'+@ratio+',
			[Y-2 (u) M1]=cast(round(f.[Y-2 (u) M1]'+@ratio+',
			[Y-2 (u) M2]=cast(round(f.[Y-2 (u) M2]'+@ratio+',
			[Y-2 (u) M3]=cast(round(f.[Y-2 (u) M3]'+@ratio+',
			[Y-2 (u) M4]=cast(round(f.[Y-2 (u) M4]'+@ratio+',
			[Y-2 (u) M5]=cast(round(f.[Y-2 (u) M5]'+@ratio+',
			[Y-2 (u) M6]=cast(round(f.[Y-2 (u) M6]'+@ratio+',
			[Y-2 (u) M7]=cast(round(f.[Y-2 (u) M7]'+@ratio+',
			[Y-2 (u) M8]=cast(round(f.[Y-2 (u) M8]'+@ratio+',
			[Y-2 (u) M9]=cast(round(f.[Y-2 (u) M9]'+@ratio+',
			[Y-2 (u) M10]=cast(round(f.[Y-2 (u) M10]'+@ratio+',
			[Y-2 (u) M11]=cast(round(f.[Y-2 (u) M11]'+@ratio+',
			[Y-2 (u) M12]=cast(round(f.[Y-2 (u) M12]'+@ratio+','
		select @sql00='
			[Y-1 (u) M1]=cast(round(f.[Y-1 (u) M1]'+@ratio+',
			[Y-1 (u) M2]=cast(round(f.[Y-1 (u) M2]'+@ratio+',
			[Y-1 (u) M3]=cast(round(f.[Y-1 (u) M3]'+@ratio+',
			[Y-1 (u) M4]=cast(round(f.[Y-1 (u) M4]'+@ratio+',
			[Y-1 (u) M5]=cast(round(f.[Y-1 (u) M5]'+@ratio+',
			[Y-1 (u) M6]=cast(round(f.[Y-1 (u) M6]'+@ratio+',
			[Y-1 (u) M7]=cast(round(f.[Y-1 (u) M7]'+@ratio+',
			[Y-1 (u) M8]=cast(round(f.[Y-1 (u) M8]'+@ratio+',
			[Y-1 (u) M9]=cast(round(f.[Y-1 (u) M9]'+@ratio+',
			[Y-1 (u) M10]=cast(round(f.[Y-1 (u) M10]'+@ratio+',
			[Y-1 (u) M11]=cast(round(f.[Y-1 (u) M11]'+@ratio+',
			[Y-1 (u) M12]=cast(round(f.[Y-1 (u) M12]'+@ratio+',
			[Y0 (u) M1]=cast(round(f.[Y0 (u) M1]'+@ratio+',
			[Y0 (u) M2]=cast(round(f.[Y0 (u) M2]'+@ratio+',
			[Y0 (u) M3]=cast(round(f.[Y0 (u) M3]'+@ratio+',
			[Y0 (u) M4]=cast(round(f.[Y0 (u) M4]'+@ratio+',
			[Y0 (u) M5]=cast(round(f.[Y0 (u) M5]'+@ratio+',
			[Y0 (u) M6]=cast(round(f.[Y0 (u) M6]'+@ratio+',
			[Y0 (u) M7]=cast(round(f.[Y0 (u) M7]'+@ratio+',
			[Y0 (u) M8]=cast(round(f.[Y0 (u) M8]'+@ratio+',
			[Y0 (u) M9]=cast(round(f.[Y0 (u) M9]'+@ratio+',
			[Y0 (u) M10]=cast(round(f.[Y0 (u) M10]'+@ratio+',
			[Y0 (u) M11]=cast(round(f.[Y0 (u) M11]'+@ratio+',
			[Y0 (u) M12]=cast(round(f.[Y0 (u) M12]'+@ratio+',
			[Y+1 (u) M1]=cast(round(f.[Y+1 (u) M1]'+@ratio+',
			[Y+1 (u) M2]=cast(round(f.[Y+1 (u) M2]'+@ratio+','
		select @sql1='
			[Y+1 (u) M3]=cast(round(f.[Y+1 (u) M3]'+@ratio+',
			[Y+1 (u) M4]=cast(round(f.[Y+1 (u) M4]'+@ratio+',
			[Y+1 (u) M5]=cast(round(f.[Y+1 (u) M5]'+@ratio+',
			[Y+1 (u) M6]=cast(round(f.[Y+1 (u) M6]'+@ratio+',
			[Y+1 (u) M7]=cast(round(f.[Y+1 (u) M7]'+@ratio+',
			[Y+1 (u) M8]=cast(round(f.[Y+1 (u) M8]'+@ratio+',
			[Y+1 (u) M9]=cast(round(f.[Y+1 (u) M9]'+@ratio+',
			[Y+1 (u) M10]=cast(round(f.[Y+1 (u) M10]'+@ratio+',
			[Y+1 (u) M11]=cast(round(f.[Y+1 (u) M11]'+@ratio+',
			[Y+1 (u) M12]=cast(round(f.[Y+1 (u) M12]'+@ratio+',
			[(m-1)_Y0 (u) M1]=cast(round(f.[(m-1)_Y0 (u) M1]'+@ratio+',
			[(m-1)_Y0 (u) M2]=cast(round(f.[(m-1)_Y0 (u) M2]'+@ratio+',
			[(m-1)_Y0 (u) M3]=cast(round(f.[(m-1)_Y0 (u) M3]'+@ratio+',
			[(m-1)_Y0 (u) M4]=cast(round(f.[(m-1)_Y0 (u) M4]'+@ratio+',
			[(m-1)_Y0 (u) M5]=cast(round(f.[(m-1)_Y0 (u) M5]'+@ratio+',
			[(m-1)_Y0 (u) M6]=cast(round(f.[(m-1)_Y0 (u) M6]'+@ratio+',
			[(m-1)_Y0 (u) M7]=cast(round(f.[(m-1)_Y0 (u) M7]'+@ratio+',
			[(m-1)_Y0 (u) M8]=cast(round(f.[(m-1)_Y0 (u) M8]'+@ratio+',
			[(m-1)_Y0 (u) M9]=cast(round(f.[(m-1)_Y0 (u) M9]'+@ratio+',
			[(m-1)_Y0 (u) M10]=cast(round(f.[(m-1)_Y0 (u) M10]'+@ratio+',
			[(m-1)_Y0 (u) M11]=cast(round(f.[(m-1)_Y0 (u) M11]'+@ratio+',
			[(m-1)_Y0 (u) M12]=cast(round(f.[(m-1)_Y0 (u) M12]'+@ratio+',
			[(m-1)_Y+1 (u) M1]=cast(round(f.[(m-1)_Y+1 (u) M1]'+@ratio+',
			[(m-1)_Y+1 (u) M2]=cast(round(f.[(m-1)_Y+1 (u) M2]'+@ratio+',
			[(m-1)_Y+1 (u) M3]=cast(round(f.[(m-1)_Y+1 (u) M3]'+@ratio+',
			[(m-1)_Y+1 (u) M4]=cast(round(f.[(m-1)_Y+1 (u) M4]'+@ratio+',
			[(m-1)_Y+1 (u) M5]=cast(round(f.[(m-1)_Y+1 (u) M5]'+@ratio+',
			[(m-1)_Y+1 (u) M6]=cast(round(f.[(m-1)_Y+1 (u) M6]'+@ratio+',
			[(m-1)_Y+1 (u) M7]=cast(round(f.[(m-1)_Y+1 (u) M7]'+@ratio+',
			[(m-1)_Y+1 (u) M8]=cast(round(f.[(m-1)_Y+1 (u) M8]'+@ratio+',
			[(m-1)_Y+1 (u) M9]=cast(round(f.[(m-1)_Y+1 (u) M9]'+@ratio+',
			[(m-1)_Y+1 (u) M10]=cast(round(f.[(m-1)_Y+1 (u) M10]'+@ratio+',
			[(m-1)_Y+1 (u) M11]=cast(round(f.[(m-1)_Y+1 (u) M11]'+@ratio+',
			[(m-1)_Y+1 (u) M12]=cast(round(f.[(m-1)_Y+1 (u) M12]'+@ratio+','
		select @sql2='
			[B_Y0_M1]=cast(round(f.[B_Y0_M1]'+@ratio+',
			[B_Y0_M2]=cast(round(f.[B_Y0_M2]'+@ratio+',
			[B_Y0_M3]=cast(round(f.[B_Y0_M3]'+@ratio+',
			[B_Y0_M4]=cast(round(f.[B_Y0_M4]'+@ratio+',
			[B_Y0_M5]=cast(round(f.[B_Y0_M5]'+@ratio+',
			[B_Y0_M6]=cast(round(f.[B_Y0_M6]'+@ratio+',
			[B_Y0_M7]=cast(round(f.[B_Y0_M7]'+@ratio+',
			[B_Y0_M8]=cast(round(f.[B_Y0_M8]'+@ratio+',
			[B_Y0_M9]=cast(round(f.[B_Y0_M9]'+@ratio+',
			[B_Y0_M10]=cast(round(f.[B_Y0_M10]'+@ratio+',
			[B_Y0_M11]=cast(round(f.[B_Y0_M11]'+@ratio+',
			[B_Y0_M12]=cast(round(f.[B_Y0_M12]'+@ratio+',
			[B_Y+1_M1]=cast(round(f.[B_Y+1_M1]'+@ratio+',
			[B_Y+1_M2]=cast(round(f.[B_Y+1_M2]'+@ratio+',
			[B_Y+1_M3]=cast(round(f.[B_Y+1_M3]'+@ratio+',
			[B_Y+1_M4]=cast(round(f.[B_Y+1_M4]'+@ratio+',
			[B_Y+1_M5]=cast(round(f.[B_Y+1_M5]'+@ratio+',
			[B_Y+1_M6]=cast(round(f.[B_Y+1_M6]'+@ratio+',
			[B_Y+1_M7]=cast(round(f.[B_Y+1_M7]'+@ratio+',
			[B_Y+1_M8]=cast(round(f.[B_Y+1_M8]'+@ratio+',
			[B_Y+1_M9]=cast(round(f.[B_Y+1_M9]'+@ratio+',
			[B_Y+1_M10]=cast(round(f.[B_Y+1_M10]'+@ratio+',
			[B_Y+1_M11]=cast(round(f.[B_Y+1_M11]'+@ratio+',
			[B_Y+1_M12]=cast(round(f.[B_Y+1_M12]'+@ratio+',
			[PB_Y+1_M1]=cast(round(f.[PB_Y+1_M1]'+@ratio+',
			[PB_Y+1_M2]=cast(round(f.[PB_Y+1_M2]'+@ratio+',
			[PB_Y+1_M3]=cast(round(f.[PB_Y+1_M3]'+@ratio+',
			[PB_Y+1_M4]=cast(round(f.[PB_Y+1_M4]'+@ratio+',
			[PB_Y+1_M5]=cast(round(f.[PB_Y+1_M5]'+@ratio+',
			[PB_Y+1_M6]=cast(round(f.[PB_Y+1_M6]'+@ratio+',
			[PB_Y+1_M7]=cast(round(f.[PB_Y+1_M7]'+@ratio+',
			[PB_Y+1_M8]=cast(round(f.[PB_Y+1_M8]'+@ratio+',
			[PB_Y+1_M9]=cast(round(f.[PB_Y+1_M9]'+@ratio+',
			[PB_Y+1_M10]=cast(round(f.[PB_Y+1_M10]'+@ratio+',
			[PB_Y+1_M11]=cast(round(f.[PB_Y+1_M11]'+@ratio+',
			[PB_Y+1_M12]=cast(round(f.[PB_Y+1_M12]'+@ratio+',
			[T1_Y0_M1]=cast(round(f.[T1_Y0_M1]'+@ratio+',
			[T1_Y0_M2]=cast(round(f.[T1_Y0_M2]'+@ratio+',
			[T1_Y0_M3]=cast(round(f.[T1_Y0_M3]'+@ratio+',
			[T1_Y0_M4]=cast(round(f.[T1_Y0_M4]'+@ratio+',
			[T1_Y0_M5]=cast(round(f.[T1_Y0_M5]'+@ratio+',
			[T1_Y0_M6]=cast(round(f.[T1_Y0_M6]'+@ratio+',
			[T1_Y0_M7]=cast(round(f.[T1_Y0_M7]'+@ratio+',
			[T1_Y0_M8]=cast(round(f.[T1_Y0_M8]'+@ratio+',
			[T1_Y0_M9]=cast(round(f.[T1_Y0_M9]'+@ratio+',
			[T1_Y0_M10]=cast(round(f.[T1_Y0_M10]'+@ratio+',
			[T1_Y0_M11]=cast(round(f.[T1_Y0_M11]'+@ratio+',
			[T1_Y0_M12]=cast(round(f.[T1_Y0_M12]'+@ratio+','
		select @sql3='
			[T2_Y0_M1]=cast(round(f.[T2_Y0_M1]'+@ratio+',
			[T2_Y0_M2]=cast(round(f.[T2_Y0_M2]'+@ratio+',
			[T2_Y0_M3]=cast(round(f.[T2_Y0_M3]'+@ratio+',
			[T2_Y0_M4]=cast(round(f.[T2_Y0_M4]'+@ratio+',
			[T2_Y0_M5]=cast(round(f.[T2_Y0_M5]'+@ratio+',
			[T2_Y0_M6]=cast(round(f.[T2_Y0_M6]'+@ratio+',
			[T2_Y0_M7]=cast(round(f.[T2_Y0_M7]'+@ratio+',
			[T2_Y0_M8]=cast(round(f.[T2_Y0_M8]'+@ratio+',
			[T2_Y0_M9]=cast(round(f.[T2_Y0_M9]'+@ratio+',
			[T2_Y0_M10]=cast(round(f.[T2_Y0_M10]'+@ratio+',
			[T2_Y0_M11]=cast(round(f.[T2_Y0_M11]'+@ratio+',
			[T2_Y0_M12]=cast(round(f.[T2_Y0_M12]'+@ratio+',
			[T3_Y0_M1]=cast(round(f.[T3_Y0_M1]'+@ratio+',
			[T3_Y0_M2]=cast(round(f.[T3_Y0_M2]'+@ratio+',
			[T3_Y0_M3]=cast(round(f.[T3_Y0_M3]'+@ratio+',
			[T3_Y0_M4]=cast(round(f.[T3_Y0_M4]'+@ratio+',
			[T3_Y0_M5]=cast(round(f.[T3_Y0_M5]'+@ratio+',
			[T3_Y0_M6]=cast(round(f.[T3_Y0_M6]'+@ratio+',
			[T3_Y0_M7]=cast(round(f.[T3_Y0_M7]'+@ratio+',
			[T3_Y0_M8]=cast(round(f.[T3_Y0_M8]'+@ratio+',
			[T3_Y0_M9]=cast(round(f.[T3_Y0_M9]'+@ratio+',
			[T3_Y0_M10]=cast(round(f.[T3_Y0_M10]'+@ratio+',
			[T3_Y0_M11]=cast(round(f.[T3_Y0_M11]'+@ratio+',
			[T3_Y0_M12]=cast(round(f.[T3_Y0_M12]'+@ratio+',
			[(Value)_Y-2 (u) M1]=cast(round(f.[(Value)_Y-2 (u) M1]'+@ratio+',
			[(Value)_Y-2 (u) M2]=cast(round(f.[(Value)_Y-2 (u) M2]'+@ratio+',
			[(Value)_Y-2 (u) M3]=cast(round(f.[(Value)_Y-2 (u) M3]'+@ratio+',
			[(Value)_Y-2 (u) M4]=cast(round(f.[(Value)_Y-2 (u) M4]'+@ratio+',
			[(Value)_Y-2 (u) M5]=cast(round(f.[(Value)_Y-2 (u) M5]'+@ratio+',
			[(Value)_Y-2 (u) M6]=cast(round(f.[(Value)_Y-2 (u) M6]'+@ratio+',
			[(Value)_Y-2 (u) M7]=cast(round(f.[(Value)_Y-2 (u) M7]'+@ratio+',
			[(Value)_Y-2 (u) M8]=cast(round(f.[(Value)_Y-2 (u) M8]'+@ratio+',
			[(Value)_Y-2 (u) M9]=cast(round(f.[(Value)_Y-2 (u) M9]'+@ratio+',
			[(Value)_Y-2 (u) M10]=cast(round(f.[(Value)_Y-2 (u) M10]'+@ratio+',
			[(Value)_Y-2 (u) M11]=cast(round(f.[(Value)_Y-2 (u) M11]'+@ratio+',
			[(Value)_Y-2 (u) M12]=cast(round(f.[(Value)_Y-2 (u) M12]'+@ratio+','
		select @sql4='
			[(Value)_Y-1 (u) M1]=cast(round(f.[(Value)_Y-1 (u) M1]'+@ratio+',
			[(Value)_Y-1 (u) M2]=cast(round(f.[(Value)_Y-1 (u) M2]'+@ratio+',
			[(Value)_Y-1 (u) M3]=cast(round(f.[(Value)_Y-1 (u) M3]'+@ratio+',
			[(Value)_Y-1 (u) M4]=cast(round(f.[(Value)_Y-1 (u) M4]'+@ratio+',
			[(Value)_Y-1 (u) M5]=cast(round(f.[(Value)_Y-1 (u) M5]'+@ratio+',
			[(Value)_Y-1 (u) M6]=cast(round(f.[(Value)_Y-1 (u) M6]'+@ratio+',
			[(Value)_Y-1 (u) M7]=cast(round(f.[(Value)_Y-1 (u) M7]'+@ratio+',
			[(Value)_Y-1 (u) M8]=cast(round(f.[(Value)_Y-1 (u) M8]'+@ratio+',
			[(Value)_Y-1 (u) M9]=cast(round(f.[(Value)_Y-1 (u) M9]'+@ratio+',
			[(Value)_Y-1 (u) M10]=cast(round(f.[(Value)_Y-1 (u) M10]'+@ratio+',
			[(Value)_Y-1 (u) M11]=cast(round(f.[(Value)_Y-1 (u) M11]'+@ratio+',
			[(Value)_Y-1 (u) M12]=cast(round(f.[(Value)_Y-1 (u) M12]'+@ratio+',
			[(Value)_Y0 (u) M1]=cast(round(f.[(Value)_Y0 (u) M1]'+@ratio+',
			[(Value)_Y0 (u) M2]=cast(round(f.[(Value)_Y0 (u) M2]'+@ratio+',
			[(Value)_Y0 (u) M3]=cast(round(f.[(Value)_Y0 (u) M3]'+@ratio+',
			[(Value)_Y0 (u) M4]=cast(round(f.[(Value)_Y0 (u) M4]'+@ratio+',
			[(Value)_Y0 (u) M5]=cast(round(f.[(Value)_Y0 (u) M5]'+@ratio+',
			[(Value)_Y0 (u) M6]=cast(round(f.[(Value)_Y0 (u) M6]'+@ratio+',
			[(Value)_Y0 (u) M7]=cast(round(f.[(Value)_Y0 (u) M7]'+@ratio+',
			[(Value)_Y0 (u) M8]=cast(round(f.[(Value)_Y0 (u) M8]'+@ratio+',
			[(Value)_Y0 (u) M9]=cast(round(f.[(Value)_Y0 (u) M9]'+@ratio+',
			[(Value)_Y0 (u) M10]=cast(round(f.[(Value)_Y0 (u) M10]'+@ratio+',
			[(Value)_Y0 (u) M11]=cast(round(f.[(Value)_Y0 (u) M11]'+@ratio+',
			[(Value)_Y0 (u) M12]=cast(round(f.[(Value)_Y0 (u) M12]'+@ratio+',
			[(Value)_Y+1 (u) M1]=cast(round(f.[(Value)_Y+1 (u) M1]'+@ratio+',
			[(Value)_Y+1 (u) M2]=cast(round(f.[(Value)_Y+1 (u) M2]'+@ratio+',
			[(Value)_Y+1 (u) M3]=cast(round(f.[(Value)_Y+1 (u) M3]'+@ratio+',
			[(Value)_Y+1 (u) M4]=cast(round(f.[(Value)_Y+1 (u) M4]'+@ratio+',
			[(Value)_Y+1 (u) M5]=cast(round(f.[(Value)_Y+1 (u) M5]'+@ratio+',
			[(Value)_Y+1 (u) M6]=cast(round(f.[(Value)_Y+1 (u) M6]'+@ratio+',
			[(Value)_Y+1 (u) M7]=cast(round(f.[(Value)_Y+1 (u) M7]'+@ratio+',
			[(Value)_Y+1 (u) M8]=cast(round(f.[(Value)_Y+1 (u) M8]'+@ratio+',
			[(Value)_Y+1 (u) M9]=cast(round(f.[(Value)_Y+1 (u) M9]'+@ratio+',
			[(Value)_Y+1 (u) M10]=cast(round(f.[(Value)_Y+1 (u) M10]'+@ratio+',
			[(Value)_Y+1 (u) M11]=cast(round(f.[(Value)_Y+1 (u) M11]'+@ratio+',
			[(Value)_Y+1 (u) M12]=cast(round(f.[(Value)_Y+1 (u) M12]'+@ratio+','
		select @sql5='
			[(Value)_(m-1)_Y0 (u) M1]=cast(round(f.[(Value)_(m-1)_Y0 (u) M1]'+@ratio+',
			[(Value)_(m-1)_Y0 (u) M2]=cast(round(f.[(Value)_(m-1)_Y0 (u) M2]'+@ratio+',
			[(Value)_(m-1)_Y0 (u) M3]=cast(round(f.[(Value)_(m-1)_Y0 (u) M3]'+@ratio+',
			[(Value)_(m-1)_Y0 (u) M4]=cast(round(f.[(Value)_(m-1)_Y0 (u) M4]'+@ratio+',
			[(Value)_(m-1)_Y0 (u) M5]=cast(round(f.[(Value)_(m-1)_Y0 (u) M5]'+@ratio+',
			[(Value)_(m-1)_Y0 (u) M6]=cast(round(f.[(Value)_(m-1)_Y0 (u) M6]'+@ratio+',
			[(Value)_(m-1)_Y0 (u) M7]=cast(round(f.[(Value)_(m-1)_Y0 (u) M7]'+@ratio+',
			[(Value)_(m-1)_Y0 (u) M8]=cast(round(f.[(Value)_(m-1)_Y0 (u) M8]'+@ratio+',
			[(Value)_(m-1)_Y0 (u) M9]=cast(round(f.[(Value)_(m-1)_Y0 (u) M9]'+@ratio+',
			[(Value)_(m-1)_Y0 (u) M10]=cast(round(f.[(Value)_(m-1)_Y0 (u) M10]'+@ratio+',
			[(Value)_(m-1)_Y0 (u) M11]=cast(round(f.[(Value)_(m-1)_Y0 (u) M11]'+@ratio+',
			[(Value)_(m-1)_Y0 (u) M12]=cast(round(f.[(Value)_(m-1)_Y0 (u) M12]'+@ratio+',
			[(Value)_(m-1)_Y+1 (u) M1]=cast(round(f.[(Value)_(m-1)_Y+1 (u) M1]'+@ratio+',
			[(Value)_(m-1)_Y+1 (u) M2]=cast(round(f.[(Value)_(m-1)_Y+1 (u) M2]'+@ratio+',
			[(Value)_(m-1)_Y+1 (u) M3]=cast(round(f.[(Value)_(m-1)_Y+1 (u) M3]'+@ratio+',
			[(Value)_(m-1)_Y+1 (u) M4]=cast(round(f.[(Value)_(m-1)_Y+1 (u) M4]'+@ratio+',
			[(Value)_(m-1)_Y+1 (u) M5]=cast(round(f.[(Value)_(m-1)_Y+1 (u) M5]'+@ratio+',
			[(Value)_(m-1)_Y+1 (u) M6]=cast(round(f.[(Value)_(m-1)_Y+1 (u) M6]'+@ratio+',
			[(Value)_(m-1)_Y+1 (u) M7]=cast(round(f.[(Value)_(m-1)_Y+1 (u) M7]'+@ratio+',
			[(Value)_(m-1)_Y+1 (u) M8]=cast(round(f.[(Value)_(m-1)_Y+1 (u) M8]'+@ratio+',
			[(Value)_(m-1)_Y+1 (u) M9]=cast(round(f.[(Value)_(m-1)_Y+1 (u) M9]'+@ratio+',
			[(Value)_(m-1)_Y+1 (u) M10]=cast(round(f.[(Value)_(m-1)_Y+1 (u) M10]'+@ratio+',
			[(Value)_(m-1)_Y+1 (u) M11]=cast(round(f.[(Value)_(m-1)_Y+1 (u) M11]'+@ratio+',
			[(Value)_(m-1)_Y+1 (u) M12]=cast(round(f.[(Value)_(m-1)_Y+1 (u) M12]'+@ratio+',
			[(Value)_B_Y0_M1]=cast(round(f.[(Value)_B_Y0_M1]'+@ratio+',
			[(Value)_B_Y0_M2]=cast(round(f.[(Value)_B_Y0_M2]'+@ratio+',
			[(Value)_B_Y0_M3]=cast(round(f.[(Value)_B_Y0_M3]'+@ratio+',
			[(Value)_B_Y0_M4]=cast(round(f.[(Value)_B_Y0_M4]'+@ratio+',
			[(Value)_B_Y0_M5]=cast(round(f.[(Value)_B_Y0_M5]'+@ratio+',
			[(Value)_B_Y0_M6]=cast(round(f.[(Value)_B_Y0_M6]'+@ratio+',
			[(Value)_B_Y0_M7]=cast(round(f.[(Value)_B_Y0_M7]'+@ratio+',
			[(Value)_B_Y0_M8]=cast(round(f.[(Value)_B_Y0_M8]'+@ratio+',
			[(Value)_B_Y0_M9]=cast(round(f.[(Value)_B_Y0_M9]'+@ratio+','
		select @sql6='
			[(Value)_B_Y0_M10]=cast(round(f.[(Value)_B_Y0_M10]'+@ratio+',
			[(Value)_B_Y0_M11]=cast(round(f.[(Value)_B_Y0_M11]'+@ratio+',
			[(Value)_B_Y0_M12]=cast(round(f.[(Value)_B_Y0_M12]'+@ratio+',
			[(Value)_B_Y+1_M1]=cast(round(f.[(Value)_B_Y+1_M1]'+@ratio+',
			[(Value)_B_Y+1_M2]=cast(round(f.[(Value)_B_Y+1_M2]'+@ratio+',
			[(Value)_B_Y+1_M3]=cast(round(f.[(Value)_B_Y+1_M3]'+@ratio+',
			[(Value)_B_Y+1_M4]=cast(round(f.[(Value)_B_Y+1_M4]'+@ratio+',
			[(Value)_B_Y+1_M5]=cast(round(f.[(Value)_B_Y+1_M5]'+@ratio+',
			[(Value)_B_Y+1_M6]=cast(round(f.[(Value)_B_Y+1_M6]'+@ratio+',
			[(Value)_B_Y+1_M7]=cast(round(f.[(Value)_B_Y+1_M7]'+@ratio+',
			[(Value)_B_Y+1_M8]=cast(round(f.[(Value)_B_Y+1_M8]'+@ratio+',
			[(Value)_B_Y+1_M9]=cast(round(f.[(Value)_B_Y+1_M9]'+@ratio+',
			[(Value)_B_Y+1_M10]=cast(round(f.[(Value)_B_Y+1_M10]'+@ratio+',
			[(Value)_B_Y+1_M11]=cast(round(f.[(Value)_B_Y+1_M11]'+@ratio+',
			[(Value)_B_Y+1_M12]=cast(round(f.[(Value)_B_Y+1_M12]'+@ratio+',
			[(Value)_PB_Y+1_M1]=cast(round(f.[(Value)_PB_Y+1_M1]'+@ratio+',
			[(Value)_PB_Y+1_M2]=cast(round(f.[(Value)_PB_Y+1_M2]'+@ratio+',
			[(Value)_PB_Y+1_M3]=cast(round(f.[(Value)_PB_Y+1_M3]'+@ratio+',
			[(Value)_PB_Y+1_M4]=cast(round(f.[(Value)_PB_Y+1_M4]'+@ratio+',
			[(Value)_PB_Y+1_M5]=cast(round(f.[(Value)_PB_Y+1_M5]'+@ratio+',
			[(Value)_PB_Y+1_M6]=cast(round(f.[(Value)_PB_Y+1_M6]'+@ratio+',
			[(Value)_PB_Y+1_M7]=cast(round(f.[(Value)_PB_Y+1_M7]'+@ratio+',
			[(Value)_PB_Y+1_M8]=cast(round(f.[(Value)_PB_Y+1_M8]'+@ratio+',
			[(Value)_PB_Y+1_M9]=cast(round(f.[(Value)_PB_Y+1_M9]'+@ratio+',
			[(Value)_PB_Y+1_M10]=cast(round(f.[(Value)_PB_Y+1_M10]'+@ratio+',
			[(Value)_PB_Y+1_M11]=cast(round(f.[(Value)_PB_Y+1_M11]'+@ratio+',
			[(Value)_PB_Y+1_M12]=cast(round(f.[(Value)_PB_Y+1_M12]'+@ratio+',
			[(Value)_T1_Y0_M1]=cast(round(f.[(Value)_T1_Y0_M1]'+@ratio+',
			[(Value)_T1_Y0_M2]=cast(round(f.[(Value)_T1_Y0_M2]'+@ratio+',
			[(Value)_T1_Y0_M3]=cast(round(f.[(Value)_T1_Y0_M3]'+@ratio+',
			[(Value)_T1_Y0_M4]=cast(round(f.[(Value)_T1_Y0_M4]'+@ratio+',
			[(Value)_T1_Y0_M5]=cast(round(f.[(Value)_T1_Y0_M5]'+@ratio+',
			[(Value)_T1_Y0_M6]=cast(round(f.[(Value)_T1_Y0_M6]'+@ratio+',
			[(Value)_T1_Y0_M7]=cast(round(f.[(Value)_T1_Y0_M7]'+@ratio+',
			[(Value)_T1_Y0_M8]=cast(round(f.[(Value)_T1_Y0_M8]'+@ratio+',
			[(Value)_T1_Y0_M9]=cast(round(f.[(Value)_T1_Y0_M9]'+@ratio+',
			[(Value)_T1_Y0_M10]=cast(round(f.[(Value)_T1_Y0_M10]'+@ratio+',
			[(Value)_T1_Y0_M11]=cast(round(f.[(Value)_T1_Y0_M11]'+@ratio+',
			[(Value)_T1_Y0_M12]=cast(round(f.[(Value)_T1_Y0_M12]'+@ratio+','
		select @sql7='
			[(Value)_T2_Y0_M1]=cast(round(f.[(Value)_T2_Y0_M1]'+@ratio+',
			[(Value)_T2_Y0_M2]=cast(round(f.[(Value)_T2_Y0_M2]'+@ratio+',
			[(Value)_T2_Y0_M3]=cast(round(f.[(Value)_T2_Y0_M3]'+@ratio+',
			[(Value)_T2_Y0_M4]=cast(round(f.[(Value)_T2_Y0_M4]'+@ratio+',
			[(Value)_T2_Y0_M5]=cast(round(f.[(Value)_T2_Y0_M5]'+@ratio+',
			[(Value)_T2_Y0_M6]=cast(round(f.[(Value)_T2_Y0_M6]'+@ratio+',
			[(Value)_T2_Y0_M7]=cast(round(f.[(Value)_T2_Y0_M7]'+@ratio+',
			[(Value)_T2_Y0_M8]=cast(round(f.[(Value)_T2_Y0_M8]'+@ratio+',
			[(Value)_T2_Y0_M9]=cast(round(f.[(Value)_T2_Y0_M9]'+@ratio+',
			[(Value)_T2_Y0_M10]=cast(round(f.[(Value)_T2_Y0_M10]'+@ratio+',
			[(Value)_T2_Y0_M11]=cast(round(f.[(Value)_T2_Y0_M11]'+@ratio+',
			[(Value)_T2_Y0_M12]=cast(round(f.[(Value)_T2_Y0_M12]'+@ratio+',
			[(Value)_T3_Y0_M1]=cast(round(f.[(Value)_T3_Y0_M1]'+@ratio+',
			[(Value)_T3_Y0_M2]=cast(round(f.[(Value)_T3_Y0_M2]'+@ratio+',
			[(Value)_T3_Y0_M3]=cast(round(f.[(Value)_T3_Y0_M3]'+@ratio+',
			[(Value)_T3_Y0_M4]=cast(round(f.[(Value)_T3_Y0_M4]'+@ratio+',
			[(Value)_T3_Y0_M5]=cast(round(f.[(Value)_T3_Y0_M5]'+@ratio+',
			[(Value)_T3_Y0_M6]=cast(round(f.[(Value)_T3_Y0_M6]'+@ratio+',
			[(Value)_T3_Y0_M7]=cast(round(f.[(Value)_T3_Y0_M7]'+@ratio+',
			[(Value)_T3_Y0_M8]=cast(round(f.[(Value)_T3_Y0_M8]'+@ratio+',
			[(Value)_T3_Y0_M9]=cast(round(f.[(Value)_T3_Y0_M9]'+@ratio+',
			[(Value)_T3_Y0_M10]=cast(round(f.[(Value)_T3_Y0_M10]'+@ratio+',
			[(Value)_T3_Y0_M11]=cast(round(f.[(Value)_T3_Y0_M11]'+@ratio+',
			[(Value)_T3_Y0_M12]=cast(round(f.[(Value)_T3_Y0_M12]'+@ratio+'
		from FC_FM_Original_'+@division+'_'+@FM_KEY+' f (NOLOCK) 
		'+case when @division='CPD' then '' else
		'left join
		(
			select distinct
				[FM_KEY],
				[Forecasting lines],
				[SUB GROUP/ Brand]
			from FC_SO_OPTIMUS_MAPPING_SUBGRP_'+@division+'
			/*where FM_KEY=(select top 1 FM_KEY from FC_ComputerName (NOLOCK) where [ComputerName]=HOST_NAME())*/
		) as o on o.[SUB GROUP/ Brand] = f.[SUB GROUP/ Brand] and f.FM_KEY=o.FM_KEY ' end
		+' left join
		(
			select DISTINCT
				[FM_KEY],
				[ref. Code],
				[SUB GROUP/ Brand],
				[% Ratio]=ISNULL([% Ratio],''1'')
			from fnc_SubGroupMaster('''+@division+''',''full'')
		) ff on ff.[Ref. Code]=f.[Ref. Code] '		

		if @debug>0
		begin
			select 
				[SQL]=(@sql0+@sql00+@sql1+@sql2+@sql3+@sql4+@sql5+@sql6+@sql7)
			,len(@sql0) 'len_@sql0',len(@sql00) 'len_@sql00', len(@sql1) 'len_@sql1'
			,len(@sql2) 'len_@sql2', len(@sql3) 'len_@sql3',len(@sql4) 'len_@sql4'
			,len(@sql5) 'len_@sql5',len(@sql6) 'len_@sql6',len(@sql7) 'len_@sql7'
		end
		execute(@sql0+@sql00+@sql1+@sql2+@sql3+@sql4+@sql5+@sql6+@sql7)
	end
	else
	begin
		select @sql1=
			'create view '+@view_name+'
			As
				Select DISTINCT
					[SO Forecasting lines]='''+case when @division='CPD' then '' else '[Forecasting lines]' end+''',
					f.[id],
					f.[Product type],
					f.[Signature],
					f.[CAT/Axe],
					f.[SUB CAT/ Sub Axe],
					f.[GROUP/ Class],
					f.[Ref. Code],
					f.[SUB GROUP/ Brand],
					f.[HERO],
					f.[Channel],
					f.[Product status],
					f.[Time series],
					f.[SIT],
					f.[SIT Day],
					f.[SOH],
					f.[MTD SI],
					f.[Total GIT],
					f.[GIT M0],
					f.[GIT M1],
					f.[GIT M2],
					f.[GIT M3],
					f.[Risk (u) M0],
					f.[Risk (u) M1],
					f.[Risk (u) M2],
					f.[Risk (u) M3],
					f.[Total risk (u)],
					f.[Risk (val) M0],
					f.[Risk (val) M1],
					f.[Risk (val) M2],
					f.[Risk (val) M3],
					f.[Total risk (val)],
					f.[AVE P3M Y-1],
					f.[AVE F3M Y-1],
					f.[AVE P3M Y0],
					f.[AVE F3M Y0],
					f.[%F3M Y0/ P3M Y0],
					f.[%F3M Y-1/ P3M Y-1],
					f.[SLOB],
					f.[Y-2 (u) M1],
					f.[Y-2 (u) M2],
					f.[Y-2 (u) M3],
					f.[Y-2 (u) M4],
					f.[Y-2 (u) M5],
					f.[Y-2 (u) M6],
					f.[Y-2 (u) M7],
					f.[Y-2 (u) M8],
					f.[Y-2 (u) M9],
					f.[Y-2 (u) M10],
					f.[Y-2 (u) M11],
					f.[Y-2 (u) M12],
					f.[Y-1 (u) M1],
					f.[Y-1 (u) M2],
					f.[Y-1 (u) M3],
					f.[Y-1 (u) M4],
					f.[Y-1 (u) M5],
					f.[Y-1 (u) M6],
					f.[Y-1 (u) M7],
					f.[Y-1 (u) M8],
					f.[Y-1 (u) M9],
					f.[Y-1 (u) M10],
					f.[Y-1 (u) M11],
					f.[Y-1 (u) M12],
					f.[Y0 (u) M1],
					f.[Y0 (u) M2],
					f.[Y0 (u) M3],
					f.[Y0 (u) M4],
					f.[Y0 (u) M5],
					f.[Y0 (u) M6],
					f.[Y0 (u) M7],
					f.[Y0 (u) M8],
					f.[Y0 (u) M9],
					f.[Y0 (u) M10],
					f.[Y0 (u) M11],
					f.[Y0 (u) M12],
					f.[Y+1 (u) M1],
					f.[Y+1 (u) M2],
					f.[Y+1 (u) M3],
					f.[Y+1 (u) M4],
					f.[Y+1 (u) M5],
					f.[Y+1 (u) M6],
					f.[Y+1 (u) M7],
					f.[Y+1 (u) M8],
					f.[Y+1 (u) M9],
					f.[Y+1 (u) M10],
					f.[Y+1 (u) M11],
					f.[Y+1 (u) M12],
					f.[(m-1)_Y0 (u) M1],
					f.[(m-1)_Y0 (u) M2],
					f.[(m-1)_Y0 (u) M3],
					f.[(m-1)_Y0 (u) M4],
					f.[(m-1)_Y0 (u) M5],
					f.[(m-1)_Y0 (u) M6],
					f.[(m-1)_Y0 (u) M7],
					f.[(m-1)_Y0 (u) M8],
					f.[(m-1)_Y0 (u) M9],
					f.[(m-1)_Y0 (u) M10],
					f.[(m-1)_Y0 (u) M11],
					f.[(m-1)_Y0 (u) M12],
					f.[(m-1)_Y+1 (u) M1],
					f.[(m-1)_Y+1 (u) M2],
					f.[(m-1)_Y+1 (u) M3],
					f.[(m-1)_Y+1 (u) M4],
					f.[(m-1)_Y+1 (u) M5],
					f.[(m-1)_Y+1 (u) M6],
					f.[(m-1)_Y+1 (u) M7],
					f.[(m-1)_Y+1 (u) M8],
					f.[(m-1)_Y+1 (u) M9],
					f.[(m-1)_Y+1 (u) M10],
					f.[(m-1)_Y+1 (u) M11],
					f.[(m-1)_Y+1 (u) M12],
					f.[B_Y0_M1],
					f.[B_Y0_M2],
					f.[B_Y0_M3],
					f.[B_Y0_M4],
					f.[B_Y0_M5],
					f.[B_Y0_M6],
					f.[B_Y0_M7],
					f.[B_Y0_M8],
					f.[B_Y0_M9],
					f.[B_Y0_M10],
					f.[B_Y0_M11],
					f.[B_Y0_M12],
					f.[B_Y+1_M1],
					f.[B_Y+1_M2],
					f.[B_Y+1_M3],
					f.[B_Y+1_M4],
					f.[B_Y+1_M5],
					f.[B_Y+1_M6],
					f.[B_Y+1_M7],
					f.[B_Y+1_M8],
					f.[B_Y+1_M9],
					f.[B_Y+1_M10],
					f.[B_Y+1_M11],
					f.[B_Y+1_M12],
					f.[PB_Y+1_M1],
					f.[PB_Y+1_M2],
					f.[PB_Y+1_M3],
					f.[PB_Y+1_M4],
					f.[PB_Y+1_M5],
					f.[PB_Y+1_M6],
					f.[PB_Y+1_M7],
					f.[PB_Y+1_M8],
					f.[PB_Y+1_M9],
					f.[PB_Y+1_M10],
					f.[PB_Y+1_M11],
					f.[PB_Y+1_M12],
					f.[T1_Y0_M1],
					f.[T1_Y0_M2],
					f.[T1_Y0_M3],
					f.[T1_Y0_M4],
					f.[T1_Y0_M5],
					f.[T1_Y0_M6],
					f.[T1_Y0_M7],
					f.[T1_Y0_M8],
					f.[T1_Y0_M9],
					f.[T1_Y0_M10],
					f.[T1_Y0_M11],
					f.[T1_Y0_M12],
					f.[T2_Y0_M1],
					f.[T2_Y0_M2],
					f.[T2_Y0_M3],
					f.[T2_Y0_M4],
					f.[T2_Y0_M5],
					f.[T2_Y0_M6],
					f.[T2_Y0_M7],
					f.[T2_Y0_M8],
					f.[T2_Y0_M9],
					f.[T2_Y0_M10],
					f.[T2_Y0_M11],
					f.[T2_Y0_M12],'
			select @sql2='
					f.[T3_Y0_M1],
					f.[T3_Y0_M2],
					f.[T3_Y0_M3],
					f.[T3_Y0_M4],
					f.[T3_Y0_M5],
					f.[T3_Y0_M6],
					f.[T3_Y0_M7],
					f.[T3_Y0_M8],
					f.[T3_Y0_M9],
					f.[T3_Y0_M10],
					f.[T3_Y0_M11],
					f.[T3_Y0_M12],
					f.[(Value)_Y-2 (u) M1],
					f.[(Value)_Y-2 (u) M2],
					f.[(Value)_Y-2 (u) M3],
					f.[(Value)_Y-2 (u) M4],
					f.[(Value)_Y-2 (u) M5],
					f.[(Value)_Y-2 (u) M6],
					f.[(Value)_Y-2 (u) M7],
					f.[(Value)_Y-2 (u) M8],
					f.[(Value)_Y-2 (u) M9],
					f.[(Value)_Y-2 (u) M10],
					f.[(Value)_Y-2 (u) M11],
					f.[(Value)_Y-2 (u) M12],
					f.[(Value)_Y-1 (u) M1],
					f.[(Value)_Y-1 (u) M2],
					f.[(Value)_Y-1 (u) M3],
					f.[(Value)_Y-1 (u) M4],
					f.[(Value)_Y-1 (u) M5],
					f.[(Value)_Y-1 (u) M6],
					f.[(Value)_Y-1 (u) M7],
					f.[(Value)_Y-1 (u) M8],
					f.[(Value)_Y-1 (u) M9],
					f.[(Value)_Y-1 (u) M10],
					f.[(Value)_Y-1 (u) M11],
					f.[(Value)_Y-1 (u) M12],
					f.[(Value)_Y0 (u) M1],
					f.[(Value)_Y0 (u) M2],
					f.[(Value)_Y0 (u) M3],
					f.[(Value)_Y0 (u) M4],
					f.[(Value)_Y0 (u) M5],
					f.[(Value)_Y0 (u) M6],
					f.[(Value)_Y0 (u) M7],
					f.[(Value)_Y0 (u) M8],
					f.[(Value)_Y0 (u) M9],
					f.[(Value)_Y0 (u) M10],
					f.[(Value)_Y0 (u) M11],
					f.[(Value)_Y0 (u) M12],
					f.[(Value)_Y+1 (u) M1],
					f.[(Value)_Y+1 (u) M2],
					f.[(Value)_Y+1 (u) M3],
					f.[(Value)_Y+1 (u) M4],
					f.[(Value)_Y+1 (u) M5],
					f.[(Value)_Y+1 (u) M6],
					f.[(Value)_Y+1 (u) M7],
					f.[(Value)_Y+1 (u) M8],
					f.[(Value)_Y+1 (u) M9],
					f.[(Value)_Y+1 (u) M10],
					f.[(Value)_Y+1 (u) M11],
					f.[(Value)_Y+1 (u) M12],
					f.[(Value)_(m-1)_Y0 (u) M1],
					f.[(Value)_(m-1)_Y0 (u) M2],
					f.[(Value)_(m-1)_Y0 (u) M3],
					f.[(Value)_(m-1)_Y0 (u) M4],
					f.[(Value)_(m-1)_Y0 (u) M5],
					f.[(Value)_(m-1)_Y0 (u) M6],
					f.[(Value)_(m-1)_Y0 (u) M7],
					f.[(Value)_(m-1)_Y0 (u) M8],
					f.[(Value)_(m-1)_Y0 (u) M9],
					f.[(Value)_(m-1)_Y0 (u) M10],
					f.[(Value)_(m-1)_Y0 (u) M11],
					f.[(Value)_(m-1)_Y0 (u) M12],
					f.[(Value)_(m-1)_Y+1 (u) M1],
					f.[(Value)_(m-1)_Y+1 (u) M2],
					f.[(Value)_(m-1)_Y+1 (u) M3],
					f.[(Value)_(m-1)_Y+1 (u) M4],
					f.[(Value)_(m-1)_Y+1 (u) M5],
					f.[(Value)_(m-1)_Y+1 (u) M6],
					f.[(Value)_(m-1)_Y+1 (u) M7],
					f.[(Value)_(m-1)_Y+1 (u) M8],
					f.[(Value)_(m-1)_Y+1 (u) M9],
					f.[(Value)_(m-1)_Y+1 (u) M10],
					f.[(Value)_(m-1)_Y+1 (u) M11],
					f.[(Value)_(m-1)_Y+1 (u) M12],'
			select @sql3='
					f.[(Value)_B_Y0_M1],
					f.[(Value)_B_Y0_M2],
					f.[(Value)_B_Y0_M3],
					f.[(Value)_B_Y0_M4],
					f.[(Value)_B_Y0_M5],
					f.[(Value)_B_Y0_M6],
					f.[(Value)_B_Y0_M7],
					f.[(Value)_B_Y0_M8],
					f.[(Value)_B_Y0_M9],
					f.[(Value)_B_Y0_M10],
					f.[(Value)_B_Y0_M11],
					f.[(Value)_B_Y0_M12],
					f.[(Value)_B_Y+1_M1],
					f.[(Value)_B_Y+1_M2],
					f.[(Value)_B_Y+1_M3],
					f.[(Value)_B_Y+1_M4],
					f.[(Value)_B_Y+1_M5],
					f.[(Value)_B_Y+1_M6],
					f.[(Value)_B_Y+1_M7],
					f.[(Value)_B_Y+1_M8],
					f.[(Value)_B_Y+1_M9],
					f.[(Value)_B_Y+1_M10],
					f.[(Value)_B_Y+1_M11],
					f.[(Value)_B_Y+1_M12],
					f.[(Value)_PB_Y+1_M1],
					f.[(Value)_PB_Y+1_M2],
					f.[(Value)_PB_Y+1_M3],
					f.[(Value)_PB_Y+1_M4],
					f.[(Value)_PB_Y+1_M5],
					f.[(Value)_PB_Y+1_M6],
					f.[(Value)_PB_Y+1_M7],
					f.[(Value)_PB_Y+1_M8],
					f.[(Value)_PB_Y+1_M9],
					f.[(Value)_PB_Y+1_M10],
					f.[(Value)_PB_Y+1_M11],
					f.[(Value)_PB_Y+1_M12],
					f.[(Value)_T1_Y0_M1],
					f.[(Value)_T1_Y0_M2],
					f.[(Value)_T1_Y0_M3],
					f.[(Value)_T1_Y0_M4],
					f.[(Value)_T1_Y0_M5],
					f.[(Value)_T1_Y0_M6],
					f.[(Value)_T1_Y0_M7],
					f.[(Value)_T1_Y0_M8],
					f.[(Value)_T1_Y0_M9],
					f.[(Value)_T1_Y0_M10],
					f.[(Value)_T1_Y0_M11],
					f.[(Value)_T1_Y0_M12],
					f.[(Value)_T2_Y0_M1],
					f.[(Value)_T2_Y0_M2],
					f.[(Value)_T2_Y0_M3],
					f.[(Value)_T2_Y0_M4],
					f.[(Value)_T2_Y0_M5],
					f.[(Value)_T2_Y0_M6],
					f.[(Value)_T2_Y0_M7],
					f.[(Value)_T2_Y0_M8],
					f.[(Value)_T2_Y0_M9],
					f.[(Value)_T2_Y0_M10],
					f.[(Value)_T2_Y0_M11],
					f.[(Value)_T2_Y0_M12],
					f.[(Value)_T3_Y0_M1],
					f.[(Value)_T3_Y0_M2],
					f.[(Value)_T3_Y0_M3],
					f.[(Value)_T3_Y0_M4],
					f.[(Value)_T3_Y0_M5],
					f.[(Value)_T3_Y0_M6],
					f.[(Value)_T3_Y0_M7],
					f.[(Value)_T3_Y0_M8],
					f.[(Value)_T3_Y0_M9],
					f.[(Value)_T3_Y0_M10],
					f.[(Value)_T3_Y0_M11],
					f.[(Value)_T3_Y0_M12]
				from FC_FM_Original_'+@division+'_'+@FM_KEY+' f (NOLOCK) 
				'+case when @division='CPD' then '' else
				'left join
				(
					select distinct
						[Forecasting lines],
						[SUB GROUP/ Brand]
					from FC_SO_OPTIMUS_MAPPING_SUBGRP_'+@division+'
					where FM_KEY=(select top 1 FM_KEY from FC_ComputerName (NOLOCK) where [ComputerName]=HOST_NAME())
				) as o on o.[SUB GROUP/ Brand] = f.[SUB GROUP/ Brand] ' end

			if @debug>0
			begin
				select @sql1+@sql2+@sql3 ,len(@sql1), len(@sql2),len(@sql3)
			end
			execute(@sql1+@sql2+@sql3)
	end
end