/*
	exec sp_get_fc_fm_original_WF 'LDB','202407','all'
*/
Alter proc sp_get_fc_fm_original_WF
	@Division		nvarchar(3),
	@FM_KEY			nvarchar(6),
	@Type			nvarchar(10)
As
begin
	declare @debug			int=0
	declare @sql			nvarchar(max)=''
	declare @sql2			nvarchar(max)=''
	declare @listcolumn		nvarchar(max)=''

	SELECT @listcolumn = ListColumn FROM fn_FC_GetColheader_Current(@FM_KEY,'UploadFM_2','f')

	if @Type='all'
	begin
		select @sql='
		select
			f.[id],
			f.[Product type],
			f.[Signature],
			f.[CAT/Axe],
			f.[SUB CAT/ Sub Axe],
			f.[GROUP/ Class],
			f.[Ref. Code],
			f.[SUB GROUP/ Brand],
			f.[HERO],
			f.[Channel],
			f.[Product status],
			f.[Time series],
			f.[SIT],
			f.[SIT Day],
			f.[SOH],
			f.[MTD SI],
			f.[Total GIT],
			f.[GIT M0],
			f.[GIT M1],
			f.[GIT M2],
			f.[GIT M3],
			'+case when @Division IN('CPD','LDB') then 'f.[Risk (u) M0],
			f.[Risk (u) M1],
			f.[Risk (u) M2],
			f.[Risk (u) M3],
			f.[Total risk (u)],
			f.[Risk (val) M0],
			f.[Risk (val) M1],
			f.[Risk (val) M2],
			f.[Risk (val) M3],
			f.[Total risk (val)],' else '' end+'
			f.[AVE P3M Y-1],
			f.[AVE F3M Y-1],
			f.[AVE P3M Y0],
			f.[AVE F3M Y0],
			f.[%F3M Y0/ P3M Y0],
			f.[%F3M Y-1/ P3M Y-1],
			f.[SLOB],
			f.[Y-2 (u) M1],
			f.[Y-2 (u) M2],
			f.[Y-2 (u) M3],
			f.[Y-2 (u) M4],
			f.[Y-2 (u) M5],
			f.[Y-2 (u) M6],
			f.[Y-2 (u) M7],
			f.[Y-2 (u) M8],
			f.[Y-2 (u) M9],
			f.[Y-2 (u) M10],
			f.[Y-2 (u) M11],
			f.[Y-2 (u) M12],
			f.[Y-1 (u) M1],
			f.[Y-1 (u) M2],
			f.[Y-1 (u) M3],
			f.[Y-1 (u) M4],
			f.[Y-1 (u) M5],
			f.[Y-1 (u) M6],
			f.[Y-1 (u) M7],
			f.[Y-1 (u) M8],
			f.[Y-1 (u) M9],
			f.[Y-1 (u) M10],
			f.[Y-1 (u) M11],
			f.[Y-1 (u) M12],
			f.[Y0 (u) M1],
			f.[Y0 (u) M2],
			f.[Y0 (u) M3],
			f.[Y0 (u) M4],
			f.[Y0 (u) M5],
			f.[Y0 (u) M6],
			f.[Y0 (u) M7],
			f.[Y0 (u) M8],
			f.[Y0 (u) M9],
			f.[Y0 (u) M10],
			f.[Y0 (u) M11],
			f.[Y0 (u) M12],
			f.[Y+1 (u) M1],
			f.[Y+1 (u) M2],
			f.[Y+1 (u) M3],
			f.[Y+1 (u) M4],
			f.[Y+1 (u) M5],
			f.[Y+1 (u) M6],
			f.[Y+1 (u) M7],
			f.[Y+1 (u) M8],
			f.[Y+1 (u) M9],
			f.[Y+1 (u) M10],
			f.[Y+1 (u) M11],
			f.[Y+1 (u) M12],
			f.[(m-1)_Y0 (u) M1],
			f.[(m-1)_Y0 (u) M2],
			f.[(m-1)_Y0 (u) M3],
			f.[(m-1)_Y0 (u) M4],
			f.[(m-1)_Y0 (u) M5],
			f.[(m-1)_Y0 (u) M6],
			f.[(m-1)_Y0 (u) M7],
			f.[(m-1)_Y0 (u) M8],
			f.[(m-1)_Y0 (u) M9],
			f.[(m-1)_Y0 (u) M10],
			f.[(m-1)_Y0 (u) M11],
			f.[(m-1)_Y0 (u) M12],
			f.[(m-1)_Y+1 (u) M1],
			f.[(m-1)_Y+1 (u) M2],
			f.[(m-1)_Y+1 (u) M3],
			f.[(m-1)_Y+1 (u) M4],
			f.[(m-1)_Y+1 (u) M5],
			f.[(m-1)_Y+1 (u) M6],
			f.[(m-1)_Y+1 (u) M7],
			f.[(m-1)_Y+1 (u) M8],
			f.[(m-1)_Y+1 (u) M9],
			f.[(m-1)_Y+1 (u) M10],
			f.[(m-1)_Y+1 (u) M11],
			f.[(m-1)_Y+1 (u) M12],
			f.[B_Y0_M1],
			f.[B_Y0_M2],
			f.[B_Y0_M3],
			f.[B_Y0_M4],
			f.[B_Y0_M5],
			f.[B_Y0_M6],
			f.[B_Y0_M7],
			f.[B_Y0_M8],
			f.[B_Y0_M9],
			f.[B_Y0_M10],
			f.[B_Y0_M11],
			f.[B_Y0_M12],
			f.[B_Y+1_M1],
			f.[B_Y+1_M2],
			f.[B_Y+1_M3],
			f.[B_Y+1_M4],
			f.[B_Y+1_M5],
			f.[B_Y+1_M6],
			f.[B_Y+1_M7],
			f.[B_Y+1_M8],
			f.[B_Y+1_M9],
			f.[B_Y+1_M10],
			f.[B_Y+1_M11],
			f.[B_Y+1_M12],
			f.[PB_Y+1_M1],
			f.[PB_Y+1_M2],
			f.[PB_Y+1_M3],
			f.[PB_Y+1_M4],
			f.[PB_Y+1_M5],
			f.[PB_Y+1_M6],
			f.[PB_Y+1_M7],
			f.[PB_Y+1_M8],
			f.[PB_Y+1_M9],
			f.[PB_Y+1_M10],
			f.[PB_Y+1_M11],
			f.[PB_Y+1_M12],
			f.[T1_Y0_M1],
			f.[T1_Y0_M2],
			f.[T1_Y0_M3],
			f.[T1_Y0_M4],
			f.[T1_Y0_M5],
			f.[T1_Y0_M6],
			f.[T1_Y0_M7],
			f.[T1_Y0_M8],
			f.[T1_Y0_M9],
			f.[T1_Y0_M10],
			f.[T1_Y0_M11],
			f.[T1_Y0_M12],
			f.[T2_Y0_M1],
			f.[T2_Y0_M2],
			f.[T2_Y0_M3],
			f.[T2_Y0_M4],
			f.[T2_Y0_M5],
			f.[T2_Y0_M6],
			f.[T2_Y0_M7],
			f.[T2_Y0_M8],
			f.[T2_Y0_M9],
			f.[T2_Y0_M10],
			f.[T2_Y0_M11],
			f.[T2_Y0_M12],
			f.[T3_Y0_M1],
			f.[T3_Y0_M2],
			f.[T3_Y0_M3],
			f.[T3_Y0_M4],
			f.[T3_Y0_M5],
			f.[T3_Y0_M6],
			f.[T3_Y0_M7],
			f.[T3_Y0_M8],
			f.[T3_Y0_M9],
			f.[T3_Y0_M10],
			f.[T3_Y0_M11],
			f.[T3_Y0_M12],
			f.[(Value)_Y-2 (u) M1],
			f.[(Value)_Y-2 (u) M2],
			f.[(Value)_Y-2 (u) M3],
			f.[(Value)_Y-2 (u) M4],
			f.[(Value)_Y-2 (u) M5],
			f.[(Value)_Y-2 (u) M6],
			f.[(Value)_Y-2 (u) M7],
			f.[(Value)_Y-2 (u) M8],
			f.[(Value)_Y-2 (u) M9],
			f.[(Value)_Y-2 (u) M10],
			f.[(Value)_Y-2 (u) M11],
			f.[(Value)_Y-2 (u) M12],
			f.[(Value)_Y-1 (u) M1],
			f.[(Value)_Y-1 (u) M2],'
		select @sql2 ='
			f.[(Value)_Y-1 (u) M3],
			f.[(Value)_Y-1 (u) M4],
			f.[(Value)_Y-1 (u) M5],
			f.[(Value)_Y-1 (u) M6],
			f.[(Value)_Y-1 (u) M7],
			f.[(Value)_Y-1 (u) M8],
			f.[(Value)_Y-1 (u) M9],
			f.[(Value)_Y-1 (u) M10],
			f.[(Value)_Y-1 (u) M11],
			f.[(Value)_Y-1 (u) M12],
			f.[(Value)_Y0 (u) M1],
			f.[(Value)_Y0 (u) M2],
			f.[(Value)_Y0 (u) M3],
			f.[(Value)_Y0 (u) M4],
			f.[(Value)_Y0 (u) M5],
			f.[(Value)_Y0 (u) M6],
			f.[(Value)_Y0 (u) M7],
			f.[(Value)_Y0 (u) M8],
			f.[(Value)_Y0 (u) M9],
			f.[(Value)_Y0 (u) M10],
			f.[(Value)_Y0 (u) M11],
			f.[(Value)_Y0 (u) M12],
			f.[(Value)_Y+1 (u) M1],
			f.[(Value)_Y+1 (u) M2],
			f.[(Value)_Y+1 (u) M3],
			f.[(Value)_Y+1 (u) M4],
			f.[(Value)_Y+1 (u) M5],
			f.[(Value)_Y+1 (u) M6],
			f.[(Value)_Y+1 (u) M7],
			f.[(Value)_Y+1 (u) M8],
			f.[(Value)_Y+1 (u) M9],
			f.[(Value)_Y+1 (u) M10],
			f.[(Value)_Y+1 (u) M11],
			f.[(Value)_Y+1 (u) M12],
			f.[(Value)_(m-1)_Y0 (u) M1],
			f.[(Value)_(m-1)_Y0 (u) M2],
			f.[(Value)_(m-1)_Y0 (u) M3],
			f.[(Value)_(m-1)_Y0 (u) M4],
			f.[(Value)_(m-1)_Y0 (u) M5],
			f.[(Value)_(m-1)_Y0 (u) M6],
			f.[(Value)_(m-1)_Y0 (u) M7],
			f.[(Value)_(m-1)_Y0 (u) M8],
			f.[(Value)_(m-1)_Y0 (u) M9],
			f.[(Value)_(m-1)_Y0 (u) M10],
			f.[(Value)_(m-1)_Y0 (u) M11],
			f.[(Value)_(m-1)_Y0 (u) M12],
			f.[(Value)_(m-1)_Y+1 (u) M1],
			f.[(Value)_(m-1)_Y+1 (u) M2],
			f.[(Value)_(m-1)_Y+1 (u) M3],
			f.[(Value)_(m-1)_Y+1 (u) M4],
			f.[(Value)_(m-1)_Y+1 (u) M5],
			f.[(Value)_(m-1)_Y+1 (u) M6],
			f.[(Value)_(m-1)_Y+1 (u) M7],
			f.[(Value)_(m-1)_Y+1 (u) M8],
			f.[(Value)_(m-1)_Y+1 (u) M9],
			f.[(Value)_(m-1)_Y+1 (u) M10],
			f.[(Value)_(m-1)_Y+1 (u) M11],
			f.[(Value)_(m-1)_Y+1 (u) M12],
			f.[(Value)_B_Y0_M1],
			f.[(Value)_B_Y0_M2],
			f.[(Value)_B_Y0_M3],
			f.[(Value)_B_Y0_M4],
			f.[(Value)_B_Y0_M5],
			f.[(Value)_B_Y0_M6],
			f.[(Value)_B_Y0_M7],
			f.[(Value)_B_Y0_M8],
			f.[(Value)_B_Y0_M9],
			f.[(Value)_B_Y0_M10],
			f.[(Value)_B_Y0_M11],
			f.[(Value)_B_Y0_M12],
			f.[(Value)_B_Y+1_M1],
			f.[(Value)_B_Y+1_M2],
			f.[(Value)_B_Y+1_M3],
			f.[(Value)_B_Y+1_M4],
			f.[(Value)_B_Y+1_M5],
			f.[(Value)_B_Y+1_M6],
			f.[(Value)_B_Y+1_M7],
			f.[(Value)_B_Y+1_M8],
			f.[(Value)_B_Y+1_M9],
			f.[(Value)_B_Y+1_M10],
			f.[(Value)_B_Y+1_M11],
			f.[(Value)_B_Y+1_M12],
			f.[(Value)_PB_Y+1_M1],
			f.[(Value)_PB_Y+1_M2],
			f.[(Value)_PB_Y+1_M3],
			f.[(Value)_PB_Y+1_M4],
			f.[(Value)_PB_Y+1_M5],
			f.[(Value)_PB_Y+1_M6],
			f.[(Value)_PB_Y+1_M7],
			f.[(Value)_PB_Y+1_M8],
			f.[(Value)_PB_Y+1_M9],
			f.[(Value)_PB_Y+1_M10],
			f.[(Value)_PB_Y+1_M11],
			f.[(Value)_PB_Y+1_M12],
			f.[(Value)_T1_Y0_M1],
			f.[(Value)_T1_Y0_M2],
			f.[(Value)_T1_Y0_M3],
			f.[(Value)_T1_Y0_M4],
			f.[(Value)_T1_Y0_M5],
			f.[(Value)_T1_Y0_M6],
			f.[(Value)_T1_Y0_M7],
			f.[(Value)_T1_Y0_M8],
			f.[(Value)_T1_Y0_M9],
			f.[(Value)_T1_Y0_M10],
			f.[(Value)_T1_Y0_M11],
			f.[(Value)_T1_Y0_M12],
			f.[(Value)_T2_Y0_M1],
			f.[(Value)_T2_Y0_M2],
			f.[(Value)_T2_Y0_M3],
			f.[(Value)_T2_Y0_M4],
			f.[(Value)_T2_Y0_M5],
			f.[(Value)_T2_Y0_M6],
			f.[(Value)_T2_Y0_M7],
			f.[(Value)_T2_Y0_M8],
			f.[(Value)_T2_Y0_M9],
			f.[(Value)_T2_Y0_M10],
			f.[(Value)_T2_Y0_M11],
			f.[(Value)_T2_Y0_M12],
			f.[(Value)_T3_Y0_M1],
			f.[(Value)_T3_Y0_M2],
			f.[(Value)_T3_Y0_M3],
			f.[(Value)_T3_Y0_M4],
			f.[(Value)_T3_Y0_M5],
			f.[(Value)_T3_Y0_M6],
			f.[(Value)_T3_Y0_M7],
			f.[(Value)_T3_Y0_M8],
			f.[(Value)_T3_Y0_M9],
			f.[(Value)_T3_Y0_M10],
			f.[(Value)_T3_Y0_M11],
			f.[(Value)_T3_Y0_M12]
		from FC_FM_Original_'+@Division+' f
		where f.FM_KEY='''+@FM_KEY+'''
		and f.[SUB GROUP/ Brand]<>''''
		order by f.id asc '
	end
	/*'+case when @Division='LLD' then 'and CAST(REPLACE(LEFT([Time series],2),''.'','''') AS INT) NOT IN(select value from string_split(''7,8,9,10,11,12'','','') ) ' else '' end+'*/
	else
	begin
		select @sql='
		select '
			/*id,'*/
			+@listcolumn+'
		from FC_FM_Original_'+@Division+' f
		where FM_KEY='''+@FM_KEY+'''
		and f.[SUB GROUP/ Brand]<>''''
		order by id asc'
	end
	/*'+case when @Division='LLD' then 'and CAST(REPLACE(LEFT([Time series],2),''.'','''') AS INT) NOT IN(select value from string_split(''7,8,9,10,11,12'','','') ) ' else '' end+'*/
	if @debug>0
	begin
		select @sql+@sql2 '@sql 1.1.1'
		select len(@sql)
		select len(@sql2)
	end
	execute(@sql+@sql2)
end

--select * from FC_FM_Original_CPD